// Code generated by ent, DO NOT EDIT.

package joinedchat

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the joinedchat type in the database.
	Label = "joined_chat"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldChatID holds the string denoting the chat_id field in the database.
	FieldChatID = "chat_id"
	// FieldChatName holds the string denoting the chat_name field in the database.
	FieldChatName = "chat_name"
	// FieldChatType holds the string denoting the chat_type field in the database.
	FieldChatType = "chat_type"
	// FieldDialogDate holds the string denoting the dialog_date field in the database.
	FieldDialogDate = "dialog_date"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the joinedchat in the database.
	Table = "joined_chats"
)

// Columns holds all SQL columns for joinedchat fields.
var Columns = []string{
	FieldID,
	FieldPlatform,
	FieldChatID,
	FieldChatName,
	FieldChatType,
	FieldDialogDate,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DefaultChatID holds the default value on creation for the "chat_id" field.
	DefaultChatID string
	// ChatIDValidator is a validator for the "chat_id" field. It is called by the builders before save.
	ChatIDValidator func(string) error
	// DefaultChatName holds the default value on creation for the "chat_name" field.
	DefaultChatName string
	// ChatNameValidator is a validator for the "chat_name" field. It is called by the builders before save.
	ChatNameValidator func(string) error
	// DefaultChatType holds the default value on creation for the "chat_type" field.
	DefaultChatType string
	// ChatTypeValidator is a validator for the "chat_type" field. It is called by the builders before save.
	ChatTypeValidator func(string) error
	// DefaultDialogDate holds the default value on creation for the "dialog_date" field.
	DefaultDialogDate int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() int64
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() int64
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() int64
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the JoinedChat queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByChatID orders the results by the chat_id field.
func ByChatID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChatID, opts...).ToFunc()
}

// ByChatName orders the results by the chat_name field.
func ByChatName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChatName, opts...).ToFunc()
}

// ByChatType orders the results by the chat_type field.
func ByChatType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChatType, opts...).ToFunc()
}

// ByDialogDate orders the results by the dialog_date field.
func ByDialogDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDialogDate, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
