// Code generated by ent, DO NOT EDIT.

package joinedchat

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/luoling8192/adk-agent/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldLTE(FieldID, id))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEQ(FieldPlatform, v))
}

// ChatID applies equality check predicate on the "chat_id" field. It's identical to ChatIDEQ.
func ChatID(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEQ(FieldChatID, v))
}

// ChatName applies equality check predicate on the "chat_name" field. It's identical to ChatNameEQ.
func ChatName(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEQ(FieldChatName, v))
}

// ChatType applies equality check predicate on the "chat_type" field. It's identical to ChatTypeEQ.
func ChatType(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEQ(FieldChatType, v))
}

// DialogDate applies equality check predicate on the "dialog_date" field. It's identical to DialogDateEQ.
func DialogDate(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEQ(FieldDialogDate, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEQ(FieldUpdatedAt, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldContainsFold(FieldPlatform, v))
}

// ChatIDEQ applies the EQ predicate on the "chat_id" field.
func ChatIDEQ(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEQ(FieldChatID, v))
}

// ChatIDNEQ applies the NEQ predicate on the "chat_id" field.
func ChatIDNEQ(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldNEQ(FieldChatID, v))
}

// ChatIDIn applies the In predicate on the "chat_id" field.
func ChatIDIn(vs ...string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldIn(FieldChatID, vs...))
}

// ChatIDNotIn applies the NotIn predicate on the "chat_id" field.
func ChatIDNotIn(vs ...string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldNotIn(FieldChatID, vs...))
}

// ChatIDGT applies the GT predicate on the "chat_id" field.
func ChatIDGT(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldGT(FieldChatID, v))
}

// ChatIDGTE applies the GTE predicate on the "chat_id" field.
func ChatIDGTE(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldGTE(FieldChatID, v))
}

// ChatIDLT applies the LT predicate on the "chat_id" field.
func ChatIDLT(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldLT(FieldChatID, v))
}

// ChatIDLTE applies the LTE predicate on the "chat_id" field.
func ChatIDLTE(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldLTE(FieldChatID, v))
}

// ChatIDContains applies the Contains predicate on the "chat_id" field.
func ChatIDContains(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldContains(FieldChatID, v))
}

// ChatIDHasPrefix applies the HasPrefix predicate on the "chat_id" field.
func ChatIDHasPrefix(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldHasPrefix(FieldChatID, v))
}

// ChatIDHasSuffix applies the HasSuffix predicate on the "chat_id" field.
func ChatIDHasSuffix(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldHasSuffix(FieldChatID, v))
}

// ChatIDEqualFold applies the EqualFold predicate on the "chat_id" field.
func ChatIDEqualFold(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEqualFold(FieldChatID, v))
}

// ChatIDContainsFold applies the ContainsFold predicate on the "chat_id" field.
func ChatIDContainsFold(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldContainsFold(FieldChatID, v))
}

// ChatNameEQ applies the EQ predicate on the "chat_name" field.
func ChatNameEQ(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEQ(FieldChatName, v))
}

// ChatNameNEQ applies the NEQ predicate on the "chat_name" field.
func ChatNameNEQ(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldNEQ(FieldChatName, v))
}

// ChatNameIn applies the In predicate on the "chat_name" field.
func ChatNameIn(vs ...string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldIn(FieldChatName, vs...))
}

// ChatNameNotIn applies the NotIn predicate on the "chat_name" field.
func ChatNameNotIn(vs ...string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldNotIn(FieldChatName, vs...))
}

// ChatNameGT applies the GT predicate on the "chat_name" field.
func ChatNameGT(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldGT(FieldChatName, v))
}

// ChatNameGTE applies the GTE predicate on the "chat_name" field.
func ChatNameGTE(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldGTE(FieldChatName, v))
}

// ChatNameLT applies the LT predicate on the "chat_name" field.
func ChatNameLT(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldLT(FieldChatName, v))
}

// ChatNameLTE applies the LTE predicate on the "chat_name" field.
func ChatNameLTE(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldLTE(FieldChatName, v))
}

// ChatNameContains applies the Contains predicate on the "chat_name" field.
func ChatNameContains(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldContains(FieldChatName, v))
}

// ChatNameHasPrefix applies the HasPrefix predicate on the "chat_name" field.
func ChatNameHasPrefix(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldHasPrefix(FieldChatName, v))
}

// ChatNameHasSuffix applies the HasSuffix predicate on the "chat_name" field.
func ChatNameHasSuffix(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldHasSuffix(FieldChatName, v))
}

// ChatNameEqualFold applies the EqualFold predicate on the "chat_name" field.
func ChatNameEqualFold(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEqualFold(FieldChatName, v))
}

// ChatNameContainsFold applies the ContainsFold predicate on the "chat_name" field.
func ChatNameContainsFold(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldContainsFold(FieldChatName, v))
}

// ChatTypeEQ applies the EQ predicate on the "chat_type" field.
func ChatTypeEQ(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEQ(FieldChatType, v))
}

// ChatTypeNEQ applies the NEQ predicate on the "chat_type" field.
func ChatTypeNEQ(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldNEQ(FieldChatType, v))
}

// ChatTypeIn applies the In predicate on the "chat_type" field.
func ChatTypeIn(vs ...string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldIn(FieldChatType, vs...))
}

// ChatTypeNotIn applies the NotIn predicate on the "chat_type" field.
func ChatTypeNotIn(vs ...string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldNotIn(FieldChatType, vs...))
}

// ChatTypeGT applies the GT predicate on the "chat_type" field.
func ChatTypeGT(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldGT(FieldChatType, v))
}

// ChatTypeGTE applies the GTE predicate on the "chat_type" field.
func ChatTypeGTE(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldGTE(FieldChatType, v))
}

// ChatTypeLT applies the LT predicate on the "chat_type" field.
func ChatTypeLT(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldLT(FieldChatType, v))
}

// ChatTypeLTE applies the LTE predicate on the "chat_type" field.
func ChatTypeLTE(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldLTE(FieldChatType, v))
}

// ChatTypeContains applies the Contains predicate on the "chat_type" field.
func ChatTypeContains(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldContains(FieldChatType, v))
}

// ChatTypeHasPrefix applies the HasPrefix predicate on the "chat_type" field.
func ChatTypeHasPrefix(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldHasPrefix(FieldChatType, v))
}

// ChatTypeHasSuffix applies the HasSuffix predicate on the "chat_type" field.
func ChatTypeHasSuffix(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldHasSuffix(FieldChatType, v))
}

// ChatTypeEqualFold applies the EqualFold predicate on the "chat_type" field.
func ChatTypeEqualFold(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEqualFold(FieldChatType, v))
}

// ChatTypeContainsFold applies the ContainsFold predicate on the "chat_type" field.
func ChatTypeContainsFold(v string) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldContainsFold(FieldChatType, v))
}

// DialogDateEQ applies the EQ predicate on the "dialog_date" field.
func DialogDateEQ(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEQ(FieldDialogDate, v))
}

// DialogDateNEQ applies the NEQ predicate on the "dialog_date" field.
func DialogDateNEQ(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldNEQ(FieldDialogDate, v))
}

// DialogDateIn applies the In predicate on the "dialog_date" field.
func DialogDateIn(vs ...int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldIn(FieldDialogDate, vs...))
}

// DialogDateNotIn applies the NotIn predicate on the "dialog_date" field.
func DialogDateNotIn(vs ...int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldNotIn(FieldDialogDate, vs...))
}

// DialogDateGT applies the GT predicate on the "dialog_date" field.
func DialogDateGT(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldGT(FieldDialogDate, v))
}

// DialogDateGTE applies the GTE predicate on the "dialog_date" field.
func DialogDateGTE(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldGTE(FieldDialogDate, v))
}

// DialogDateLT applies the LT predicate on the "dialog_date" field.
func DialogDateLT(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldLT(FieldDialogDate, v))
}

// DialogDateLTE applies the LTE predicate on the "dialog_date" field.
func DialogDateLTE(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldLTE(FieldDialogDate, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v int64) predicate.JoinedChat {
	return predicate.JoinedChat(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.JoinedChat) predicate.JoinedChat {
	return predicate.JoinedChat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.JoinedChat) predicate.JoinedChat {
	return predicate.JoinedChat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.JoinedChat) predicate.JoinedChat {
	return predicate.JoinedChat(sql.NotPredicates(p))
}
