// Code generated by ent, DO NOT EDIT.

package event

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the event type in the database.
	Label = "event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldFromName holds the string denoting the from_name field in the database.
	FieldFromName = "from_name"
	// FieldInChatID holds the string denoting the in_chat_id field in the database.
	FieldInChatID = "in_chat_id"
	// FieldInChatType holds the string denoting the in_chat_type field in the database.
	FieldInChatType = "in_chat_type"
	// FieldPlatformTimestamp holds the string denoting the platform_timestamp field in the database.
	FieldPlatformTimestamp = "platform_timestamp"
	// FieldEvidenceMessageIds holds the string denoting the evidence_message_ids field in the database.
	FieldEvidenceMessageIds = "evidence_message_ids"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeIdentities holds the string denoting the identities edge name in mutations.
	EdgeIdentities = "identities"
	// Table holds the table name of the event in the database.
	Table = "events"
	// IdentitiesTable is the table that holds the identities relation/edge. The primary key declared below.
	IdentitiesTable = "identity_events"
	// IdentitiesInverseTable is the table name for the Identity entity.
	// It exists in this package in order to avoid circular dependency with the "identity" package.
	IdentitiesInverseTable = "identities"
)

// Columns holds all SQL columns for event fields.
var Columns = []string{
	FieldID,
	FieldPlatform,
	FieldName,
	FieldTags,
	FieldDescription,
	FieldFromName,
	FieldInChatID,
	FieldInChatType,
	FieldPlatformTimestamp,
	FieldEvidenceMessageIds,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// IdentitiesPrimaryKey and IdentitiesColumn2 are the table columns denoting the
	// primary key for the identities relation (M2M).
	IdentitiesPrimaryKey = []string{"identity_id", "event_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultFromName holds the default value on creation for the "from_name" field.
	DefaultFromName string
	// FromNameValidator is a validator for the "from_name" field. It is called by the builders before save.
	FromNameValidator func(string) error
	// DefaultInChatID holds the default value on creation for the "in_chat_id" field.
	DefaultInChatID string
	// InChatIDValidator is a validator for the "in_chat_id" field. It is called by the builders before save.
	InChatIDValidator func(string) error
	// DefaultInChatType holds the default value on creation for the "in_chat_type" field.
	DefaultInChatType string
	// InChatTypeValidator is a validator for the "in_chat_type" field. It is called by the builders before save.
	InChatTypeValidator func(string) error
	// DefaultPlatformTimestamp holds the default value on creation for the "platform_timestamp" field.
	DefaultPlatformTimestamp int64
	// DefaultEvidenceMessageIds holds the default value on creation for the "evidence_message_ids" field.
	DefaultEvidenceMessageIds []uuid.UUID
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() int64
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() int64
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() int64
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Event queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByFromName orders the results by the from_name field.
func ByFromName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromName, opts...).ToFunc()
}

// ByInChatID orders the results by the in_chat_id field.
func ByInChatID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInChatID, opts...).ToFunc()
}

// ByInChatType orders the results by the in_chat_type field.
func ByInChatType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInChatType, opts...).ToFunc()
}

// ByPlatformTimestamp orders the results by the platform_timestamp field.
func ByPlatformTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatformTimestamp, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByIdentitiesCount orders the results by identities count.
func ByIdentitiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newIdentitiesStep(), opts...)
	}
}

// ByIdentities orders the results by identities terms.
func ByIdentities(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIdentitiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newIdentitiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IdentitiesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, IdentitiesTable, IdentitiesPrimaryKey...),
	)
}
