// Code generated by ent, DO NOT EDIT.

package event

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/luoling8192/mindwave/ent/internal"
	"github.com/luoling8192/mindwave/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldID, id))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldPlatform, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldDescription, v))
}

// FromName applies equality check predicate on the "from_name" field. It's identical to FromNameEQ.
func FromName(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldFromName, v))
}

// InChatID applies equality check predicate on the "in_chat_id" field. It's identical to InChatIDEQ.
func InChatID(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldInChatID, v))
}

// InChatType applies equality check predicate on the "in_chat_type" field. It's identical to InChatTypeEQ.
func InChatType(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldInChatType, v))
}

// PlatformTimestamp applies equality check predicate on the "platform_timestamp" field. It's identical to PlatformTimestampEQ.
func PlatformTimestamp(v int64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldPlatformTimestamp, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v int64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldUpdatedAt, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldPlatform, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldName, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldTags))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldDescription, v))
}

// FromNameEQ applies the EQ predicate on the "from_name" field.
func FromNameEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldFromName, v))
}

// FromNameNEQ applies the NEQ predicate on the "from_name" field.
func FromNameNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldFromName, v))
}

// FromNameIn applies the In predicate on the "from_name" field.
func FromNameIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldFromName, vs...))
}

// FromNameNotIn applies the NotIn predicate on the "from_name" field.
func FromNameNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldFromName, vs...))
}

// FromNameGT applies the GT predicate on the "from_name" field.
func FromNameGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldFromName, v))
}

// FromNameGTE applies the GTE predicate on the "from_name" field.
func FromNameGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldFromName, v))
}

// FromNameLT applies the LT predicate on the "from_name" field.
func FromNameLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldFromName, v))
}

// FromNameLTE applies the LTE predicate on the "from_name" field.
func FromNameLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldFromName, v))
}

// FromNameContains applies the Contains predicate on the "from_name" field.
func FromNameContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldFromName, v))
}

// FromNameHasPrefix applies the HasPrefix predicate on the "from_name" field.
func FromNameHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldFromName, v))
}

// FromNameHasSuffix applies the HasSuffix predicate on the "from_name" field.
func FromNameHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldFromName, v))
}

// FromNameEqualFold applies the EqualFold predicate on the "from_name" field.
func FromNameEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldFromName, v))
}

// FromNameContainsFold applies the ContainsFold predicate on the "from_name" field.
func FromNameContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldFromName, v))
}

// InChatIDEQ applies the EQ predicate on the "in_chat_id" field.
func InChatIDEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldInChatID, v))
}

// InChatIDNEQ applies the NEQ predicate on the "in_chat_id" field.
func InChatIDNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldInChatID, v))
}

// InChatIDIn applies the In predicate on the "in_chat_id" field.
func InChatIDIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldInChatID, vs...))
}

// InChatIDNotIn applies the NotIn predicate on the "in_chat_id" field.
func InChatIDNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldInChatID, vs...))
}

// InChatIDGT applies the GT predicate on the "in_chat_id" field.
func InChatIDGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldInChatID, v))
}

// InChatIDGTE applies the GTE predicate on the "in_chat_id" field.
func InChatIDGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldInChatID, v))
}

// InChatIDLT applies the LT predicate on the "in_chat_id" field.
func InChatIDLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldInChatID, v))
}

// InChatIDLTE applies the LTE predicate on the "in_chat_id" field.
func InChatIDLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldInChatID, v))
}

// InChatIDContains applies the Contains predicate on the "in_chat_id" field.
func InChatIDContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldInChatID, v))
}

// InChatIDHasPrefix applies the HasPrefix predicate on the "in_chat_id" field.
func InChatIDHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldInChatID, v))
}

// InChatIDHasSuffix applies the HasSuffix predicate on the "in_chat_id" field.
func InChatIDHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldInChatID, v))
}

// InChatIDEqualFold applies the EqualFold predicate on the "in_chat_id" field.
func InChatIDEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldInChatID, v))
}

// InChatIDContainsFold applies the ContainsFold predicate on the "in_chat_id" field.
func InChatIDContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldInChatID, v))
}

// InChatTypeEQ applies the EQ predicate on the "in_chat_type" field.
func InChatTypeEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldInChatType, v))
}

// InChatTypeNEQ applies the NEQ predicate on the "in_chat_type" field.
func InChatTypeNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldInChatType, v))
}

// InChatTypeIn applies the In predicate on the "in_chat_type" field.
func InChatTypeIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldInChatType, vs...))
}

// InChatTypeNotIn applies the NotIn predicate on the "in_chat_type" field.
func InChatTypeNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldInChatType, vs...))
}

// InChatTypeGT applies the GT predicate on the "in_chat_type" field.
func InChatTypeGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldInChatType, v))
}

// InChatTypeGTE applies the GTE predicate on the "in_chat_type" field.
func InChatTypeGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldInChatType, v))
}

// InChatTypeLT applies the LT predicate on the "in_chat_type" field.
func InChatTypeLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldInChatType, v))
}

// InChatTypeLTE applies the LTE predicate on the "in_chat_type" field.
func InChatTypeLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldInChatType, v))
}

// InChatTypeContains applies the Contains predicate on the "in_chat_type" field.
func InChatTypeContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldInChatType, v))
}

// InChatTypeHasPrefix applies the HasPrefix predicate on the "in_chat_type" field.
func InChatTypeHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldInChatType, v))
}

// InChatTypeHasSuffix applies the HasSuffix predicate on the "in_chat_type" field.
func InChatTypeHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldInChatType, v))
}

// InChatTypeEqualFold applies the EqualFold predicate on the "in_chat_type" field.
func InChatTypeEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldInChatType, v))
}

// InChatTypeContainsFold applies the ContainsFold predicate on the "in_chat_type" field.
func InChatTypeContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldInChatType, v))
}

// PlatformTimestampEQ applies the EQ predicate on the "platform_timestamp" field.
func PlatformTimestampEQ(v int64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldPlatformTimestamp, v))
}

// PlatformTimestampNEQ applies the NEQ predicate on the "platform_timestamp" field.
func PlatformTimestampNEQ(v int64) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldPlatformTimestamp, v))
}

// PlatformTimestampIn applies the In predicate on the "platform_timestamp" field.
func PlatformTimestampIn(vs ...int64) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldPlatformTimestamp, vs...))
}

// PlatformTimestampNotIn applies the NotIn predicate on the "platform_timestamp" field.
func PlatformTimestampNotIn(vs ...int64) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldPlatformTimestamp, vs...))
}

// PlatformTimestampGT applies the GT predicate on the "platform_timestamp" field.
func PlatformTimestampGT(v int64) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldPlatformTimestamp, v))
}

// PlatformTimestampGTE applies the GTE predicate on the "platform_timestamp" field.
func PlatformTimestampGTE(v int64) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldPlatformTimestamp, v))
}

// PlatformTimestampLT applies the LT predicate on the "platform_timestamp" field.
func PlatformTimestampLT(v int64) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldPlatformTimestamp, v))
}

// PlatformTimestampLTE applies the LTE predicate on the "platform_timestamp" field.
func PlatformTimestampLTE(v int64) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldPlatformTimestamp, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v int64) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v int64) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...int64) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...int64) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v int64) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v int64) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v int64) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v int64) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasIdentities applies the HasEdge predicate on the "identities" edge.
func HasIdentities() predicate.Event {
	return predicate.Event(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, IdentitiesTable, IdentitiesPrimaryKey...),
		)
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Identity
		step.Edge.Schema = schemaConfig.IdentityEvents
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIdentitiesWith applies the HasEdge predicate on the "identities" edge with a given conditions (other predicates).
func HasIdentitiesWith(preds ...predicate.Identity) predicate.Event {
	return predicate.Event(func(s *sql.Selector) {
		step := newIdentitiesStep()
		schemaConfig := internal.SchemaConfigFromContext(s.Context())
		step.To.Schema = schemaConfig.Identity
		step.Edge.Schema = schemaConfig.IdentityEvents
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Event) predicate.Event {
	return predicate.Event(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Event) predicate.Event {
	return predicate.Event(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Event) predicate.Event {
	return predicate.Event(sql.NotPredicates(p))
}
