// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChatMessagesColumns holds the columns for the "chat_messages" table.
	ChatMessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "platform", Type: field.TypeString, Default: ""},
		{Name: "platform_message_id", Type: field.TypeString, Default: ""},
		{Name: "from_id", Type: field.TypeString, Default: ""},
		{Name: "from_name", Type: field.TypeString, Default: ""},
		{Name: "from_user_uuid", Type: field.TypeUUID, Nullable: true},
		{Name: "owner_account_id", Type: field.TypeUUID, Nullable: true},
		{Name: "in_chat_id", Type: field.TypeString, Default: ""},
		{Name: "in_chat_type", Type: field.TypeString, Default: ""},
		{Name: "content", Type: field.TypeString, Default: ""},
		{Name: "is_reply", Type: field.TypeBool, Default: false},
		{Name: "reply_to_name", Type: field.TypeString, Default: ""},
		{Name: "reply_to_id", Type: field.TypeString, Default: ""},
		{Name: "platform_timestamp", Type: field.TypeInt64, Default: 0},
		{Name: "jieba_tokens", Type: field.TypeJSON},
	}
	// ChatMessagesTable holds the schema information for the "chat_messages" table.
	ChatMessagesTable = &schema.Table{
		Name:       "chat_messages",
		Columns:    ChatMessagesColumns,
		PrimaryKey: []*schema.Column{ChatMessagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "chatmessage_platform_platform_message_id_in_chat_id_owner_account_id",
				Unique:  true,
				Columns: []*schema.Column{ChatMessagesColumns[1], ChatMessagesColumns[2], ChatMessagesColumns[7], ChatMessagesColumns[6]},
			},
			{
				Name:    "chatmessage_jieba_tokens",
				Unique:  false,
				Columns: []*schema.Column{ChatMessagesColumns[14]},
			},
			{
				Name:    "chatmessage_from_user_uuid",
				Unique:  false,
				Columns: []*schema.Column{ChatMessagesColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChatMessagesTable,
	}
)

func init() {
}
