// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/luoling8192/mindwave/ent/chatmessage"
	"github.com/luoling8192/mindwave/ent/internal"
	"github.com/luoling8192/mindwave/ent/predicate"
	pgvector "github.com/pgvector/pgvector-go"
)

// ChatMessageUpdate is the builder for updating ChatMessage entities.
type ChatMessageUpdate struct {
	config
	hooks    []Hook
	mutation *ChatMessageMutation
}

// Where appends a list predicates to the ChatMessageUpdate builder.
func (_u *ChatMessageUpdate) Where(ps ...predicate.ChatMessage) *ChatMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ChatMessageUpdate) SetPlatform(v string) *ChatMessageUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillablePlatform(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetPlatformMessageID sets the "platform_message_id" field.
func (_u *ChatMessageUpdate) SetPlatformMessageID(v string) *ChatMessageUpdate {
	_u.mutation.SetPlatformMessageID(v)
	return _u
}

// SetNillablePlatformMessageID sets the "platform_message_id" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillablePlatformMessageID(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetPlatformMessageID(*v)
	}
	return _u
}

// SetFromID sets the "from_id" field.
func (_u *ChatMessageUpdate) SetFromID(v string) *ChatMessageUpdate {
	_u.mutation.SetFromID(v)
	return _u
}

// SetNillableFromID sets the "from_id" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableFromID(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetFromID(*v)
	}
	return _u
}

// SetFromName sets the "from_name" field.
func (_u *ChatMessageUpdate) SetFromName(v string) *ChatMessageUpdate {
	_u.mutation.SetFromName(v)
	return _u
}

// SetNillableFromName sets the "from_name" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableFromName(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetFromName(*v)
	}
	return _u
}

// SetFromUserUUID sets the "from_user_uuid" field.
func (_u *ChatMessageUpdate) SetFromUserUUID(v uuid.UUID) *ChatMessageUpdate {
	_u.mutation.SetFromUserUUID(v)
	return _u
}

// SetNillableFromUserUUID sets the "from_user_uuid" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableFromUserUUID(v *uuid.UUID) *ChatMessageUpdate {
	if v != nil {
		_u.SetFromUserUUID(*v)
	}
	return _u
}

// ClearFromUserUUID clears the value of the "from_user_uuid" field.
func (_u *ChatMessageUpdate) ClearFromUserUUID() *ChatMessageUpdate {
	_u.mutation.ClearFromUserUUID()
	return _u
}

// SetOwnerAccountID sets the "owner_account_id" field.
func (_u *ChatMessageUpdate) SetOwnerAccountID(v uuid.UUID) *ChatMessageUpdate {
	_u.mutation.SetOwnerAccountID(v)
	return _u
}

// SetNillableOwnerAccountID sets the "owner_account_id" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableOwnerAccountID(v *uuid.UUID) *ChatMessageUpdate {
	if v != nil {
		_u.SetOwnerAccountID(*v)
	}
	return _u
}

// ClearOwnerAccountID clears the value of the "owner_account_id" field.
func (_u *ChatMessageUpdate) ClearOwnerAccountID() *ChatMessageUpdate {
	_u.mutation.ClearOwnerAccountID()
	return _u
}

// SetInChatID sets the "in_chat_id" field.
func (_u *ChatMessageUpdate) SetInChatID(v string) *ChatMessageUpdate {
	_u.mutation.SetInChatID(v)
	return _u
}

// SetNillableInChatID sets the "in_chat_id" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableInChatID(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetInChatID(*v)
	}
	return _u
}

// SetInChatType sets the "in_chat_type" field.
func (_u *ChatMessageUpdate) SetInChatType(v string) *ChatMessageUpdate {
	_u.mutation.SetInChatType(v)
	return _u
}

// SetNillableInChatType sets the "in_chat_type" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableInChatType(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetInChatType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ChatMessageUpdate) SetContent(v string) *ChatMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableContent(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetIsReply sets the "is_reply" field.
func (_u *ChatMessageUpdate) SetIsReply(v bool) *ChatMessageUpdate {
	_u.mutation.SetIsReply(v)
	return _u
}

// SetNillableIsReply sets the "is_reply" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableIsReply(v *bool) *ChatMessageUpdate {
	if v != nil {
		_u.SetIsReply(*v)
	}
	return _u
}

// SetReplyToName sets the "reply_to_name" field.
func (_u *ChatMessageUpdate) SetReplyToName(v string) *ChatMessageUpdate {
	_u.mutation.SetReplyToName(v)
	return _u
}

// SetNillableReplyToName sets the "reply_to_name" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableReplyToName(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetReplyToName(*v)
	}
	return _u
}

// SetReplyToID sets the "reply_to_id" field.
func (_u *ChatMessageUpdate) SetReplyToID(v string) *ChatMessageUpdate {
	_u.mutation.SetReplyToID(v)
	return _u
}

// SetNillableReplyToID sets the "reply_to_id" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableReplyToID(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetReplyToID(*v)
	}
	return _u
}

// SetPlatformTimestamp sets the "platform_timestamp" field.
func (_u *ChatMessageUpdate) SetPlatformTimestamp(v int64) *ChatMessageUpdate {
	_u.mutation.ResetPlatformTimestamp()
	_u.mutation.SetPlatformTimestamp(v)
	return _u
}

// SetNillablePlatformTimestamp sets the "platform_timestamp" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillablePlatformTimestamp(v *int64) *ChatMessageUpdate {
	if v != nil {
		_u.SetPlatformTimestamp(*v)
	}
	return _u
}

// AddPlatformTimestamp adds value to the "platform_timestamp" field.
func (_u *ChatMessageUpdate) AddPlatformTimestamp(v int64) *ChatMessageUpdate {
	_u.mutation.AddPlatformTimestamp(v)
	return _u
}

// SetContentVector1536 sets the "content_vector_1536" field.
func (_u *ChatMessageUpdate) SetContentVector1536(v pgvector.Vector) *ChatMessageUpdate {
	_u.mutation.SetContentVector1536(v)
	return _u
}

// SetNillableContentVector1536 sets the "content_vector_1536" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableContentVector1536(v *pgvector.Vector) *ChatMessageUpdate {
	if v != nil {
		_u.SetContentVector1536(*v)
	}
	return _u
}

// SetContentVector1024 sets the "content_vector_1024" field.
func (_u *ChatMessageUpdate) SetContentVector1024(v pgvector.Vector) *ChatMessageUpdate {
	_u.mutation.SetContentVector1024(v)
	return _u
}

// SetNillableContentVector1024 sets the "content_vector_1024" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableContentVector1024(v *pgvector.Vector) *ChatMessageUpdate {
	if v != nil {
		_u.SetContentVector1024(*v)
	}
	return _u
}

// SetContentVector768 sets the "content_vector_768" field.
func (_u *ChatMessageUpdate) SetContentVector768(v pgvector.Vector) *ChatMessageUpdate {
	_u.mutation.SetContentVector768(v)
	return _u
}

// SetNillableContentVector768 sets the "content_vector_768" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableContentVector768(v *pgvector.Vector) *ChatMessageUpdate {
	if v != nil {
		_u.SetContentVector768(*v)
	}
	return _u
}

// SetJiebaTokens sets the "jieba_tokens" field.
func (_u *ChatMessageUpdate) SetJiebaTokens(v []string) *ChatMessageUpdate {
	_u.mutation.SetJiebaTokens(v)
	return _u
}

// AppendJiebaTokens appends value to the "jieba_tokens" field.
func (_u *ChatMessageUpdate) AppendJiebaTokens(v []string) *ChatMessageUpdate {
	_u.mutation.AppendJiebaTokens(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ChatMessageUpdate) SetCreatedAt(v int64) *ChatMessageUpdate {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableCreatedAt(v *int64) *ChatMessageUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *ChatMessageUpdate) AddCreatedAt(v int64) *ChatMessageUpdate {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatMessageUpdate) SetUpdatedAt(v int64) *ChatMessageUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *ChatMessageUpdate) AddUpdatedAt(v int64) *ChatMessageUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChatMessageUpdate) SetDeletedAt(v int64) *ChatMessageUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableDeletedAt(v *int64) *ChatMessageUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ChatMessageUpdate) AddDeletedAt(v int64) *ChatMessageUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// Mutation returns the ChatMessageMutation object of the builder.
func (_u *ChatMessageUpdate) Mutation() *ChatMessageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChatMessageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChatMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatMessageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chatmessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatMessageUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := chatmessage.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlatformMessageID(); ok {
		if err := chatmessage.PlatformMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "platform_message_id", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.platform_message_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FromID(); ok {
		if err := chatmessage.FromIDValidator(v); err != nil {
			return &ValidationError{Name: "from_id", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.from_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FromName(); ok {
		if err := chatmessage.FromNameValidator(v); err != nil {
			return &ValidationError{Name: "from_name", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.from_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InChatID(); ok {
		if err := chatmessage.InChatIDValidator(v); err != nil {
			return &ValidationError{Name: "in_chat_id", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.in_chat_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InChatType(); ok {
		if err := chatmessage.InChatTypeValidator(v); err != nil {
			return &ValidationError{Name: "in_chat_type", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.in_chat_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := chatmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReplyToName(); ok {
		if err := chatmessage.ReplyToNameValidator(v); err != nil {
			return &ValidationError{Name: "reply_to_name", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.reply_to_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReplyToID(); ok {
		if err := chatmessage.ReplyToIDValidator(v); err != nil {
			return &ValidationError{Name: "reply_to_id", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.reply_to_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ChatMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatmessage.Table, chatmessage.Columns, sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(chatmessage.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformMessageID(); ok {
		_spec.SetField(chatmessage.FieldPlatformMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromID(); ok {
		_spec.SetField(chatmessage.FieldFromID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromName(); ok {
		_spec.SetField(chatmessage.FieldFromName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromUserUUID(); ok {
		_spec.SetField(chatmessage.FieldFromUserUUID, field.TypeUUID, value)
	}
	if _u.mutation.FromUserUUIDCleared() {
		_spec.ClearField(chatmessage.FieldFromUserUUID, field.TypeUUID)
	}
	if value, ok := _u.mutation.OwnerAccountID(); ok {
		_spec.SetField(chatmessage.FieldOwnerAccountID, field.TypeUUID, value)
	}
	if _u.mutation.OwnerAccountIDCleared() {
		_spec.ClearField(chatmessage.FieldOwnerAccountID, field.TypeUUID)
	}
	if value, ok := _u.mutation.InChatID(); ok {
		_spec.SetField(chatmessage.FieldInChatID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InChatType(); ok {
		_spec.SetField(chatmessage.FieldInChatType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(chatmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsReply(); ok {
		_spec.SetField(chatmessage.FieldIsReply, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReplyToName(); ok {
		_spec.SetField(chatmessage.FieldReplyToName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReplyToID(); ok {
		_spec.SetField(chatmessage.FieldReplyToID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformTimestamp(); ok {
		_spec.SetField(chatmessage.FieldPlatformTimestamp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlatformTimestamp(); ok {
		_spec.AddField(chatmessage.FieldPlatformTimestamp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ContentVector1536(); ok {
		_spec.SetField(chatmessage.FieldContentVector1536, field.TypeOther, value)
	}
	if value, ok := _u.mutation.ContentVector1024(); ok {
		_spec.SetField(chatmessage.FieldContentVector1024, field.TypeOther, value)
	}
	if value, ok := _u.mutation.ContentVector768(); ok {
		_spec.SetField(chatmessage.FieldContentVector768, field.TypeOther, value)
	}
	if value, ok := _u.mutation.JiebaTokens(); ok {
		_spec.SetField(chatmessage.FieldJiebaTokens, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedJiebaTokens(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, chatmessage.FieldJiebaTokens, value)
		})
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(chatmessage.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(chatmessage.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatmessage.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(chatmessage.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(chatmessage.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(chatmessage.FieldDeletedAt, field.TypeInt64, value)
	}
	_spec.Node.Schema = _u.schemaConfig.ChatMessage
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChatMessageUpdateOne is the builder for updating a single ChatMessage entity.
type ChatMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatMessageMutation
}

// SetPlatform sets the "platform" field.
func (_u *ChatMessageUpdateOne) SetPlatform(v string) *ChatMessageUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillablePlatform(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetPlatformMessageID sets the "platform_message_id" field.
func (_u *ChatMessageUpdateOne) SetPlatformMessageID(v string) *ChatMessageUpdateOne {
	_u.mutation.SetPlatformMessageID(v)
	return _u
}

// SetNillablePlatformMessageID sets the "platform_message_id" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillablePlatformMessageID(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetPlatformMessageID(*v)
	}
	return _u
}

// SetFromID sets the "from_id" field.
func (_u *ChatMessageUpdateOne) SetFromID(v string) *ChatMessageUpdateOne {
	_u.mutation.SetFromID(v)
	return _u
}

// SetNillableFromID sets the "from_id" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableFromID(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetFromID(*v)
	}
	return _u
}

// SetFromName sets the "from_name" field.
func (_u *ChatMessageUpdateOne) SetFromName(v string) *ChatMessageUpdateOne {
	_u.mutation.SetFromName(v)
	return _u
}

// SetNillableFromName sets the "from_name" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableFromName(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetFromName(*v)
	}
	return _u
}

// SetFromUserUUID sets the "from_user_uuid" field.
func (_u *ChatMessageUpdateOne) SetFromUserUUID(v uuid.UUID) *ChatMessageUpdateOne {
	_u.mutation.SetFromUserUUID(v)
	return _u
}

// SetNillableFromUserUUID sets the "from_user_uuid" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableFromUserUUID(v *uuid.UUID) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetFromUserUUID(*v)
	}
	return _u
}

// ClearFromUserUUID clears the value of the "from_user_uuid" field.
func (_u *ChatMessageUpdateOne) ClearFromUserUUID() *ChatMessageUpdateOne {
	_u.mutation.ClearFromUserUUID()
	return _u
}

// SetOwnerAccountID sets the "owner_account_id" field.
func (_u *ChatMessageUpdateOne) SetOwnerAccountID(v uuid.UUID) *ChatMessageUpdateOne {
	_u.mutation.SetOwnerAccountID(v)
	return _u
}

// SetNillableOwnerAccountID sets the "owner_account_id" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableOwnerAccountID(v *uuid.UUID) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetOwnerAccountID(*v)
	}
	return _u
}

// ClearOwnerAccountID clears the value of the "owner_account_id" field.
func (_u *ChatMessageUpdateOne) ClearOwnerAccountID() *ChatMessageUpdateOne {
	_u.mutation.ClearOwnerAccountID()
	return _u
}

// SetInChatID sets the "in_chat_id" field.
func (_u *ChatMessageUpdateOne) SetInChatID(v string) *ChatMessageUpdateOne {
	_u.mutation.SetInChatID(v)
	return _u
}

// SetNillableInChatID sets the "in_chat_id" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableInChatID(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetInChatID(*v)
	}
	return _u
}

// SetInChatType sets the "in_chat_type" field.
func (_u *ChatMessageUpdateOne) SetInChatType(v string) *ChatMessageUpdateOne {
	_u.mutation.SetInChatType(v)
	return _u
}

// SetNillableInChatType sets the "in_chat_type" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableInChatType(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetInChatType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ChatMessageUpdateOne) SetContent(v string) *ChatMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableContent(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetIsReply sets the "is_reply" field.
func (_u *ChatMessageUpdateOne) SetIsReply(v bool) *ChatMessageUpdateOne {
	_u.mutation.SetIsReply(v)
	return _u
}

// SetNillableIsReply sets the "is_reply" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableIsReply(v *bool) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetIsReply(*v)
	}
	return _u
}

// SetReplyToName sets the "reply_to_name" field.
func (_u *ChatMessageUpdateOne) SetReplyToName(v string) *ChatMessageUpdateOne {
	_u.mutation.SetReplyToName(v)
	return _u
}

// SetNillableReplyToName sets the "reply_to_name" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableReplyToName(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetReplyToName(*v)
	}
	return _u
}

// SetReplyToID sets the "reply_to_id" field.
func (_u *ChatMessageUpdateOne) SetReplyToID(v string) *ChatMessageUpdateOne {
	_u.mutation.SetReplyToID(v)
	return _u
}

// SetNillableReplyToID sets the "reply_to_id" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableReplyToID(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetReplyToID(*v)
	}
	return _u
}

// SetPlatformTimestamp sets the "platform_timestamp" field.
func (_u *ChatMessageUpdateOne) SetPlatformTimestamp(v int64) *ChatMessageUpdateOne {
	_u.mutation.ResetPlatformTimestamp()
	_u.mutation.SetPlatformTimestamp(v)
	return _u
}

// SetNillablePlatformTimestamp sets the "platform_timestamp" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillablePlatformTimestamp(v *int64) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetPlatformTimestamp(*v)
	}
	return _u
}

// AddPlatformTimestamp adds value to the "platform_timestamp" field.
func (_u *ChatMessageUpdateOne) AddPlatformTimestamp(v int64) *ChatMessageUpdateOne {
	_u.mutation.AddPlatformTimestamp(v)
	return _u
}

// SetContentVector1536 sets the "content_vector_1536" field.
func (_u *ChatMessageUpdateOne) SetContentVector1536(v pgvector.Vector) *ChatMessageUpdateOne {
	_u.mutation.SetContentVector1536(v)
	return _u
}

// SetNillableContentVector1536 sets the "content_vector_1536" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableContentVector1536(v *pgvector.Vector) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetContentVector1536(*v)
	}
	return _u
}

// SetContentVector1024 sets the "content_vector_1024" field.
func (_u *ChatMessageUpdateOne) SetContentVector1024(v pgvector.Vector) *ChatMessageUpdateOne {
	_u.mutation.SetContentVector1024(v)
	return _u
}

// SetNillableContentVector1024 sets the "content_vector_1024" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableContentVector1024(v *pgvector.Vector) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetContentVector1024(*v)
	}
	return _u
}

// SetContentVector768 sets the "content_vector_768" field.
func (_u *ChatMessageUpdateOne) SetContentVector768(v pgvector.Vector) *ChatMessageUpdateOne {
	_u.mutation.SetContentVector768(v)
	return _u
}

// SetNillableContentVector768 sets the "content_vector_768" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableContentVector768(v *pgvector.Vector) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetContentVector768(*v)
	}
	return _u
}

// SetJiebaTokens sets the "jieba_tokens" field.
func (_u *ChatMessageUpdateOne) SetJiebaTokens(v []string) *ChatMessageUpdateOne {
	_u.mutation.SetJiebaTokens(v)
	return _u
}

// AppendJiebaTokens appends value to the "jieba_tokens" field.
func (_u *ChatMessageUpdateOne) AppendJiebaTokens(v []string) *ChatMessageUpdateOne {
	_u.mutation.AppendJiebaTokens(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ChatMessageUpdateOne) SetCreatedAt(v int64) *ChatMessageUpdateOne {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableCreatedAt(v *int64) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *ChatMessageUpdateOne) AddCreatedAt(v int64) *ChatMessageUpdateOne {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatMessageUpdateOne) SetUpdatedAt(v int64) *ChatMessageUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *ChatMessageUpdateOne) AddUpdatedAt(v int64) *ChatMessageUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChatMessageUpdateOne) SetDeletedAt(v int64) *ChatMessageUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableDeletedAt(v *int64) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ChatMessageUpdateOne) AddDeletedAt(v int64) *ChatMessageUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// Mutation returns the ChatMessageMutation object of the builder.
func (_u *ChatMessageUpdateOne) Mutation() *ChatMessageMutation {
	return _u.mutation
}

// Where appends a list predicates to the ChatMessageUpdate builder.
func (_u *ChatMessageUpdateOne) Where(ps ...predicate.ChatMessage) *ChatMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChatMessageUpdateOne) Select(field string, fields ...string) *ChatMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChatMessage entity.
func (_u *ChatMessageUpdateOne) Save(ctx context.Context) (*ChatMessage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatMessageUpdateOne) SaveX(ctx context.Context) *ChatMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChatMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatMessageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chatmessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatMessageUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := chatmessage.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlatformMessageID(); ok {
		if err := chatmessage.PlatformMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "platform_message_id", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.platform_message_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FromID(); ok {
		if err := chatmessage.FromIDValidator(v); err != nil {
			return &ValidationError{Name: "from_id", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.from_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FromName(); ok {
		if err := chatmessage.FromNameValidator(v); err != nil {
			return &ValidationError{Name: "from_name", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.from_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InChatID(); ok {
		if err := chatmessage.InChatIDValidator(v); err != nil {
			return &ValidationError{Name: "in_chat_id", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.in_chat_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InChatType(); ok {
		if err := chatmessage.InChatTypeValidator(v); err != nil {
			return &ValidationError{Name: "in_chat_type", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.in_chat_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := chatmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReplyToName(); ok {
		if err := chatmessage.ReplyToNameValidator(v); err != nil {
			return &ValidationError{Name: "reply_to_name", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.reply_to_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReplyToID(); ok {
		if err := chatmessage.ReplyToIDValidator(v); err != nil {
			return &ValidationError{Name: "reply_to_id", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.reply_to_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ChatMessageUpdateOne) sqlSave(ctx context.Context) (_node *ChatMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatmessage.Table, chatmessage.Columns, sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChatMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatmessage.FieldID)
		for _, f := range fields {
			if !chatmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(chatmessage.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformMessageID(); ok {
		_spec.SetField(chatmessage.FieldPlatformMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromID(); ok {
		_spec.SetField(chatmessage.FieldFromID, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromName(); ok {
		_spec.SetField(chatmessage.FieldFromName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromUserUUID(); ok {
		_spec.SetField(chatmessage.FieldFromUserUUID, field.TypeUUID, value)
	}
	if _u.mutation.FromUserUUIDCleared() {
		_spec.ClearField(chatmessage.FieldFromUserUUID, field.TypeUUID)
	}
	if value, ok := _u.mutation.OwnerAccountID(); ok {
		_spec.SetField(chatmessage.FieldOwnerAccountID, field.TypeUUID, value)
	}
	if _u.mutation.OwnerAccountIDCleared() {
		_spec.ClearField(chatmessage.FieldOwnerAccountID, field.TypeUUID)
	}
	if value, ok := _u.mutation.InChatID(); ok {
		_spec.SetField(chatmessage.FieldInChatID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InChatType(); ok {
		_spec.SetField(chatmessage.FieldInChatType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(chatmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsReply(); ok {
		_spec.SetField(chatmessage.FieldIsReply, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReplyToName(); ok {
		_spec.SetField(chatmessage.FieldReplyToName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReplyToID(); ok {
		_spec.SetField(chatmessage.FieldReplyToID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformTimestamp(); ok {
		_spec.SetField(chatmessage.FieldPlatformTimestamp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlatformTimestamp(); ok {
		_spec.AddField(chatmessage.FieldPlatformTimestamp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ContentVector1536(); ok {
		_spec.SetField(chatmessage.FieldContentVector1536, field.TypeOther, value)
	}
	if value, ok := _u.mutation.ContentVector1024(); ok {
		_spec.SetField(chatmessage.FieldContentVector1024, field.TypeOther, value)
	}
	if value, ok := _u.mutation.ContentVector768(); ok {
		_spec.SetField(chatmessage.FieldContentVector768, field.TypeOther, value)
	}
	if value, ok := _u.mutation.JiebaTokens(); ok {
		_spec.SetField(chatmessage.FieldJiebaTokens, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedJiebaTokens(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, chatmessage.FieldJiebaTokens, value)
		})
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(chatmessage.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(chatmessage.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatmessage.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(chatmessage.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(chatmessage.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(chatmessage.FieldDeletedAt, field.TypeInt64, value)
	}
	_spec.Node.Schema = _u.schemaConfig.ChatMessage
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &ChatMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
