// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/luoling8192/adk-agent/ent/chatmessage"
)

// ChatMessage is the model entity for the ChatMessage schema.
type ChatMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// PlatformMessageID holds the value of the "platform_message_id" field.
	PlatformMessageID string `json:"platform_message_id,omitempty"`
	// FromID holds the value of the "from_id" field.
	FromID string `json:"from_id,omitempty"`
	// FromName holds the value of the "from_name" field.
	FromName string `json:"from_name,omitempty"`
	// FromUserUUID holds the value of the "from_user_uuid" field.
	FromUserUUID *uuid.UUID `json:"from_user_uuid,omitempty"`
	// OwnerAccountID holds the value of the "owner_account_id" field.
	OwnerAccountID *uuid.UUID `json:"owner_account_id,omitempty"`
	// InChatID holds the value of the "in_chat_id" field.
	InChatID string `json:"in_chat_id,omitempty"`
	// InChatType holds the value of the "in_chat_type" field.
	InChatType string `json:"in_chat_type,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// IsReply holds the value of the "is_reply" field.
	IsReply bool `json:"is_reply,omitempty"`
	// ReplyToName holds the value of the "reply_to_name" field.
	ReplyToName string `json:"reply_to_name,omitempty"`
	// ReplyToID holds the value of the "reply_to_id" field.
	ReplyToID string `json:"reply_to_id,omitempty"`
	// PlatformTimestamp holds the value of the "platform_timestamp" field.
	PlatformTimestamp int64 `json:"platform_timestamp,omitempty"`
	// JiebaTokens holds the value of the "jieba_tokens" field.
	JiebaTokens  []string `json:"jieba_tokens,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChatMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chatmessage.FieldFromUserUUID, chatmessage.FieldOwnerAccountID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case chatmessage.FieldJiebaTokens:
			values[i] = new([]byte)
		case chatmessage.FieldIsReply:
			values[i] = new(sql.NullBool)
		case chatmessage.FieldPlatformTimestamp:
			values[i] = new(sql.NullInt64)
		case chatmessage.FieldPlatform, chatmessage.FieldPlatformMessageID, chatmessage.FieldFromID, chatmessage.FieldFromName, chatmessage.FieldInChatID, chatmessage.FieldInChatType, chatmessage.FieldContent, chatmessage.FieldReplyToName, chatmessage.FieldReplyToID:
			values[i] = new(sql.NullString)
		case chatmessage.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChatMessage fields.
func (_m *ChatMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chatmessage.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case chatmessage.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case chatmessage.FieldPlatformMessageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform_message_id", values[i])
			} else if value.Valid {
				_m.PlatformMessageID = value.String
			}
		case chatmessage.FieldFromID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_id", values[i])
			} else if value.Valid {
				_m.FromID = value.String
			}
		case chatmessage.FieldFromName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_name", values[i])
			} else if value.Valid {
				_m.FromName = value.String
			}
		case chatmessage.FieldFromUserUUID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field from_user_uuid", values[i])
			} else if value.Valid {
				_m.FromUserUUID = new(uuid.UUID)
				*_m.FromUserUUID = *value.S.(*uuid.UUID)
			}
		case chatmessage.FieldOwnerAccountID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field owner_account_id", values[i])
			} else if value.Valid {
				_m.OwnerAccountID = new(uuid.UUID)
				*_m.OwnerAccountID = *value.S.(*uuid.UUID)
			}
		case chatmessage.FieldInChatID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field in_chat_id", values[i])
			} else if value.Valid {
				_m.InChatID = value.String
			}
		case chatmessage.FieldInChatType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field in_chat_type", values[i])
			} else if value.Valid {
				_m.InChatType = value.String
			}
		case chatmessage.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case chatmessage.FieldIsReply:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_reply", values[i])
			} else if value.Valid {
				_m.IsReply = value.Bool
			}
		case chatmessage.FieldReplyToName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reply_to_name", values[i])
			} else if value.Valid {
				_m.ReplyToName = value.String
			}
		case chatmessage.FieldReplyToID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reply_to_id", values[i])
			} else if value.Valid {
				_m.ReplyToID = value.String
			}
		case chatmessage.FieldPlatformTimestamp:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field platform_timestamp", values[i])
			} else if value.Valid {
				_m.PlatformTimestamp = value.Int64
			}
		case chatmessage.FieldJiebaTokens:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field jieba_tokens", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.JiebaTokens); err != nil {
					return fmt.Errorf("unmarshal field jieba_tokens: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChatMessage.
// This includes values selected through modifiers, order, etc.
func (_m *ChatMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ChatMessage.
// Note that you need to call ChatMessage.Unwrap() before calling this method if this ChatMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChatMessage) Update() *ChatMessageUpdateOne {
	return NewChatMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChatMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChatMessage) Unwrap() *ChatMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChatMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChatMessage) String() string {
	var builder strings.Builder
	builder.WriteString("ChatMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("platform_message_id=")
	builder.WriteString(_m.PlatformMessageID)
	builder.WriteString(", ")
	builder.WriteString("from_id=")
	builder.WriteString(_m.FromID)
	builder.WriteString(", ")
	builder.WriteString("from_name=")
	builder.WriteString(_m.FromName)
	builder.WriteString(", ")
	if v := _m.FromUserUUID; v != nil {
		builder.WriteString("from_user_uuid=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OwnerAccountID; v != nil {
		builder.WriteString("owner_account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("in_chat_id=")
	builder.WriteString(_m.InChatID)
	builder.WriteString(", ")
	builder.WriteString("in_chat_type=")
	builder.WriteString(_m.InChatType)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("is_reply=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsReply))
	builder.WriteString(", ")
	builder.WriteString("reply_to_name=")
	builder.WriteString(_m.ReplyToName)
	builder.WriteString(", ")
	builder.WriteString("reply_to_id=")
	builder.WriteString(_m.ReplyToID)
	builder.WriteString(", ")
	builder.WriteString("platform_timestamp=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlatformTimestamp))
	builder.WriteString(", ")
	builder.WriteString("jieba_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.JiebaTokens))
	builder.WriteByte(')')
	return builder.String()
}

// ChatMessages is a parsable slice of ChatMessage.
type ChatMessages []*ChatMessage
