// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/luoling8192/adk-agent/ent/event"
	"github.com/luoling8192/adk-agent/ent/identity"
	"github.com/luoling8192/adk-agent/ent/internal"
	"github.com/luoling8192/adk-agent/ent/predicate"
)

// EventUpdate is the builder for updating Event entities.
type EventUpdate struct {
	config
	hooks    []Hook
	mutation *EventMutation
}

// Where appends a list predicates to the EventUpdate builder.
func (_u *EventUpdate) Where(ps ...predicate.Event) *EventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *EventUpdate) SetPlatform(v string) *EventUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *EventUpdate) SetNillablePlatform(v *string) *EventUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *EventUpdate) SetName(v string) *EventUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EventUpdate) SetNillableName(v *string) *EventUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *EventUpdate) SetTags(v []string) *EventUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *EventUpdate) AppendTags(v []string) *EventUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *EventUpdate) ClearTags() *EventUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetDescription sets the "description" field.
func (_u *EventUpdate) SetDescription(v string) *EventUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *EventUpdate) SetNillableDescription(v *string) *EventUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetFromName sets the "from_name" field.
func (_u *EventUpdate) SetFromName(v string) *EventUpdate {
	_u.mutation.SetFromName(v)
	return _u
}

// SetNillableFromName sets the "from_name" field if the given value is not nil.
func (_u *EventUpdate) SetNillableFromName(v *string) *EventUpdate {
	if v != nil {
		_u.SetFromName(*v)
	}
	return _u
}

// SetInChatID sets the "in_chat_id" field.
func (_u *EventUpdate) SetInChatID(v string) *EventUpdate {
	_u.mutation.SetInChatID(v)
	return _u
}

// SetNillableInChatID sets the "in_chat_id" field if the given value is not nil.
func (_u *EventUpdate) SetNillableInChatID(v *string) *EventUpdate {
	if v != nil {
		_u.SetInChatID(*v)
	}
	return _u
}

// SetInChatType sets the "in_chat_type" field.
func (_u *EventUpdate) SetInChatType(v string) *EventUpdate {
	_u.mutation.SetInChatType(v)
	return _u
}

// SetNillableInChatType sets the "in_chat_type" field if the given value is not nil.
func (_u *EventUpdate) SetNillableInChatType(v *string) *EventUpdate {
	if v != nil {
		_u.SetInChatType(*v)
	}
	return _u
}

// SetPlatformTimestamp sets the "platform_timestamp" field.
func (_u *EventUpdate) SetPlatformTimestamp(v int64) *EventUpdate {
	_u.mutation.ResetPlatformTimestamp()
	_u.mutation.SetPlatformTimestamp(v)
	return _u
}

// SetNillablePlatformTimestamp sets the "platform_timestamp" field if the given value is not nil.
func (_u *EventUpdate) SetNillablePlatformTimestamp(v *int64) *EventUpdate {
	if v != nil {
		_u.SetPlatformTimestamp(*v)
	}
	return _u
}

// AddPlatformTimestamp adds value to the "platform_timestamp" field.
func (_u *EventUpdate) AddPlatformTimestamp(v int64) *EventUpdate {
	_u.mutation.AddPlatformTimestamp(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EventUpdate) SetCreatedAt(v int64) *EventUpdate {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EventUpdate) SetNillableCreatedAt(v *int64) *EventUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *EventUpdate) AddCreatedAt(v int64) *EventUpdate {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EventUpdate) SetUpdatedAt(v int64) *EventUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *EventUpdate) AddUpdatedAt(v int64) *EventUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// AddIdentityIDs adds the "identities" edge to the Identity entity by IDs.
func (_u *EventUpdate) AddIdentityIDs(ids ...uuid.UUID) *EventUpdate {
	_u.mutation.AddIdentityIDs(ids...)
	return _u
}

// AddIdentities adds the "identities" edges to the Identity entity.
func (_u *EventUpdate) AddIdentities(v ...*Identity) *EventUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIdentityIDs(ids...)
}

// Mutation returns the EventMutation object of the builder.
func (_u *EventUpdate) Mutation() *EventMutation {
	return _u.mutation
}

// ClearIdentities clears all "identities" edges to the Identity entity.
func (_u *EventUpdate) ClearIdentities() *EventUpdate {
	_u.mutation.ClearIdentities()
	return _u
}

// RemoveIdentityIDs removes the "identities" edge to Identity entities by IDs.
func (_u *EventUpdate) RemoveIdentityIDs(ids ...uuid.UUID) *EventUpdate {
	_u.mutation.RemoveIdentityIDs(ids...)
	return _u
}

// RemoveIdentities removes "identities" edges to Identity entities.
func (_u *EventUpdate) RemoveIdentities(v ...*Identity) *EventUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIdentityIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EventUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EventUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := event.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := event.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Event.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := event.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Event.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := event.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Event.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FromName(); ok {
		if err := event.FromNameValidator(v); err != nil {
			return &ValidationError{Name: "from_name", err: fmt.Errorf(`ent: validator failed for field "Event.from_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InChatID(); ok {
		if err := event.InChatIDValidator(v); err != nil {
			return &ValidationError{Name: "in_chat_id", err: fmt.Errorf(`ent: validator failed for field "Event.in_chat_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InChatType(); ok {
		if err := event.InChatTypeValidator(v); err != nil {
			return &ValidationError{Name: "in_chat_type", err: fmt.Errorf(`ent: validator failed for field "Event.in_chat_type": %w`, err)}
		}
	}
	return nil
}

func (_u *EventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(event.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(event.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(event.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, event.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(event.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(event.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromName(); ok {
		_spec.SetField(event.FieldFromName, field.TypeString, value)
	}
	if value, ok := _u.mutation.InChatID(); ok {
		_spec.SetField(event.FieldInChatID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InChatType(); ok {
		_spec.SetField(event.FieldInChatType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformTimestamp(); ok {
		_spec.SetField(event.FieldPlatformTimestamp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlatformTimestamp(); ok {
		_spec.AddField(event.FieldPlatformTimestamp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(event.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(event.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(event.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(event.FieldUpdatedAt, field.TypeInt64, value)
	}
	if _u.mutation.IdentitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   event.IdentitiesTable,
			Columns: event.IdentitiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(identity.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.IdentityEvents
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIdentitiesIDs(); len(nodes) > 0 && !_u.mutation.IdentitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   event.IdentitiesTable,
			Columns: event.IdentitiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(identity.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.IdentityEvents
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IdentitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   event.IdentitiesTable,
			Columns: event.IdentitiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(identity.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.IdentityEvents
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Event
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EventUpdateOne is the builder for updating a single Event entity.
type EventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventMutation
}

// SetPlatform sets the "platform" field.
func (_u *EventUpdateOne) SetPlatform(v string) *EventUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillablePlatform(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *EventUpdateOne) SetName(v string) *EventUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableName(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *EventUpdateOne) SetTags(v []string) *EventUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *EventUpdateOne) AppendTags(v []string) *EventUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *EventUpdateOne) ClearTags() *EventUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetDescription sets the "description" field.
func (_u *EventUpdateOne) SetDescription(v string) *EventUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableDescription(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetFromName sets the "from_name" field.
func (_u *EventUpdateOne) SetFromName(v string) *EventUpdateOne {
	_u.mutation.SetFromName(v)
	return _u
}

// SetNillableFromName sets the "from_name" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableFromName(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetFromName(*v)
	}
	return _u
}

// SetInChatID sets the "in_chat_id" field.
func (_u *EventUpdateOne) SetInChatID(v string) *EventUpdateOne {
	_u.mutation.SetInChatID(v)
	return _u
}

// SetNillableInChatID sets the "in_chat_id" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableInChatID(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetInChatID(*v)
	}
	return _u
}

// SetInChatType sets the "in_chat_type" field.
func (_u *EventUpdateOne) SetInChatType(v string) *EventUpdateOne {
	_u.mutation.SetInChatType(v)
	return _u
}

// SetNillableInChatType sets the "in_chat_type" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableInChatType(v *string) *EventUpdateOne {
	if v != nil {
		_u.SetInChatType(*v)
	}
	return _u
}

// SetPlatformTimestamp sets the "platform_timestamp" field.
func (_u *EventUpdateOne) SetPlatformTimestamp(v int64) *EventUpdateOne {
	_u.mutation.ResetPlatformTimestamp()
	_u.mutation.SetPlatformTimestamp(v)
	return _u
}

// SetNillablePlatformTimestamp sets the "platform_timestamp" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillablePlatformTimestamp(v *int64) *EventUpdateOne {
	if v != nil {
		_u.SetPlatformTimestamp(*v)
	}
	return _u
}

// AddPlatformTimestamp adds value to the "platform_timestamp" field.
func (_u *EventUpdateOne) AddPlatformTimestamp(v int64) *EventUpdateOne {
	_u.mutation.AddPlatformTimestamp(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EventUpdateOne) SetCreatedAt(v int64) *EventUpdateOne {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EventUpdateOne) SetNillableCreatedAt(v *int64) *EventUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *EventUpdateOne) AddCreatedAt(v int64) *EventUpdateOne {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EventUpdateOne) SetUpdatedAt(v int64) *EventUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *EventUpdateOne) AddUpdatedAt(v int64) *EventUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// AddIdentityIDs adds the "identities" edge to the Identity entity by IDs.
func (_u *EventUpdateOne) AddIdentityIDs(ids ...uuid.UUID) *EventUpdateOne {
	_u.mutation.AddIdentityIDs(ids...)
	return _u
}

// AddIdentities adds the "identities" edges to the Identity entity.
func (_u *EventUpdateOne) AddIdentities(v ...*Identity) *EventUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIdentityIDs(ids...)
}

// Mutation returns the EventMutation object of the builder.
func (_u *EventUpdateOne) Mutation() *EventMutation {
	return _u.mutation
}

// ClearIdentities clears all "identities" edges to the Identity entity.
func (_u *EventUpdateOne) ClearIdentities() *EventUpdateOne {
	_u.mutation.ClearIdentities()
	return _u
}

// RemoveIdentityIDs removes the "identities" edge to Identity entities by IDs.
func (_u *EventUpdateOne) RemoveIdentityIDs(ids ...uuid.UUID) *EventUpdateOne {
	_u.mutation.RemoveIdentityIDs(ids...)
	return _u
}

// RemoveIdentities removes "identities" edges to Identity entities.
func (_u *EventUpdateOne) RemoveIdentities(v ...*Identity) *EventUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIdentityIDs(ids...)
}

// Where appends a list predicates to the EventUpdate builder.
func (_u *EventUpdateOne) Where(ps ...predicate.Event) *EventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EventUpdateOne) Select(field string, fields ...string) *EventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Event entity.
func (_u *EventUpdateOne) Save(ctx context.Context) (*Event, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventUpdateOne) SaveX(ctx context.Context) *Event {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EventUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := event.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := event.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Event.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := event.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Event.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := event.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Event.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FromName(); ok {
		if err := event.FromNameValidator(v); err != nil {
			return &ValidationError{Name: "from_name", err: fmt.Errorf(`ent: validator failed for field "Event.from_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InChatID(); ok {
		if err := event.InChatIDValidator(v); err != nil {
			return &ValidationError{Name: "in_chat_id", err: fmt.Errorf(`ent: validator failed for field "Event.in_chat_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InChatType(); ok {
		if err := event.InChatTypeValidator(v); err != nil {
			return &ValidationError{Name: "in_chat_type", err: fmt.Errorf(`ent: validator failed for field "Event.in_chat_type": %w`, err)}
		}
	}
	return nil
}

func (_u *EventUpdateOne) sqlSave(ctx context.Context) (_node *Event, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Event.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, event.FieldID)
		for _, f := range fields {
			if !event.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != event.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(event.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(event.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(event.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, event.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(event.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(event.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromName(); ok {
		_spec.SetField(event.FieldFromName, field.TypeString, value)
	}
	if value, ok := _u.mutation.InChatID(); ok {
		_spec.SetField(event.FieldInChatID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InChatType(); ok {
		_spec.SetField(event.FieldInChatType, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformTimestamp(); ok {
		_spec.SetField(event.FieldPlatformTimestamp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPlatformTimestamp(); ok {
		_spec.AddField(event.FieldPlatformTimestamp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(event.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(event.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(event.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(event.FieldUpdatedAt, field.TypeInt64, value)
	}
	if _u.mutation.IdentitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   event.IdentitiesTable,
			Columns: event.IdentitiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(identity.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.IdentityEvents
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIdentitiesIDs(); len(nodes) > 0 && !_u.mutation.IdentitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   event.IdentitiesTable,
			Columns: event.IdentitiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(identity.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.IdentityEvents
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IdentitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   event.IdentitiesTable,
			Columns: event.IdentitiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(identity.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.IdentityEvents
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Event
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Event{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
