// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/luoling8192/mindwave/ent/event"
	"github.com/luoling8192/mindwave/ent/identity"
)

// EventCreate is the builder for creating a Event entity.
type EventCreate struct {
	config
	mutation *EventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPlatform sets the "platform" field.
func (_c *EventCreate) SetPlatform(v string) *EventCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *EventCreate) SetNillablePlatform(v *string) *EventCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *EventCreate) SetName(v string) *EventCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *EventCreate) SetNillableName(v *string) *EventCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *EventCreate) SetTags(v []string) *EventCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *EventCreate) SetDescription(v string) *EventCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *EventCreate) SetNillableDescription(v *string) *EventCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetFromName sets the "from_name" field.
func (_c *EventCreate) SetFromName(v string) *EventCreate {
	_c.mutation.SetFromName(v)
	return _c
}

// SetNillableFromName sets the "from_name" field if the given value is not nil.
func (_c *EventCreate) SetNillableFromName(v *string) *EventCreate {
	if v != nil {
		_c.SetFromName(*v)
	}
	return _c
}

// SetInChatID sets the "in_chat_id" field.
func (_c *EventCreate) SetInChatID(v string) *EventCreate {
	_c.mutation.SetInChatID(v)
	return _c
}

// SetNillableInChatID sets the "in_chat_id" field if the given value is not nil.
func (_c *EventCreate) SetNillableInChatID(v *string) *EventCreate {
	if v != nil {
		_c.SetInChatID(*v)
	}
	return _c
}

// SetInChatType sets the "in_chat_type" field.
func (_c *EventCreate) SetInChatType(v string) *EventCreate {
	_c.mutation.SetInChatType(v)
	return _c
}

// SetNillableInChatType sets the "in_chat_type" field if the given value is not nil.
func (_c *EventCreate) SetNillableInChatType(v *string) *EventCreate {
	if v != nil {
		_c.SetInChatType(*v)
	}
	return _c
}

// SetPlatformTimestamp sets the "platform_timestamp" field.
func (_c *EventCreate) SetPlatformTimestamp(v int64) *EventCreate {
	_c.mutation.SetPlatformTimestamp(v)
	return _c
}

// SetNillablePlatformTimestamp sets the "platform_timestamp" field if the given value is not nil.
func (_c *EventCreate) SetNillablePlatformTimestamp(v *int64) *EventCreate {
	if v != nil {
		_c.SetPlatformTimestamp(*v)
	}
	return _c
}

// SetEvidenceMessageIds sets the "evidence_message_ids" field.
func (_c *EventCreate) SetEvidenceMessageIds(v []uuid.UUID) *EventCreate {
	_c.mutation.SetEvidenceMessageIds(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EventCreate) SetCreatedAt(v int64) *EventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EventCreate) SetNillableCreatedAt(v *int64) *EventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EventCreate) SetUpdatedAt(v int64) *EventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EventCreate) SetNillableUpdatedAt(v *int64) *EventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EventCreate) SetID(v uuid.UUID) *EventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *EventCreate) SetNillableID(v *uuid.UUID) *EventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddIdentityIDs adds the "identities" edge to the Identity entity by IDs.
func (_c *EventCreate) AddIdentityIDs(ids ...uuid.UUID) *EventCreate {
	_c.mutation.AddIdentityIDs(ids...)
	return _c
}

// AddIdentities adds the "identities" edges to the Identity entity.
func (_c *EventCreate) AddIdentities(v ...*Identity) *EventCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddIdentityIDs(ids...)
}

// Mutation returns the EventMutation object of the builder.
func (_c *EventCreate) Mutation() *EventMutation {
	return _c.mutation
}

// Save creates the Event in the database.
func (_c *EventCreate) Save(ctx context.Context) (*Event, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventCreate) SaveX(ctx context.Context) *Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EventCreate) defaults() {
	if _, ok := _c.mutation.Platform(); !ok {
		v := event.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.Name(); !ok {
		v := event.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := event.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.FromName(); !ok {
		v := event.DefaultFromName
		_c.mutation.SetFromName(v)
	}
	if _, ok := _c.mutation.InChatID(); !ok {
		v := event.DefaultInChatID
		_c.mutation.SetInChatID(v)
	}
	if _, ok := _c.mutation.InChatType(); !ok {
		v := event.DefaultInChatType
		_c.mutation.SetInChatType(v)
	}
	if _, ok := _c.mutation.PlatformTimestamp(); !ok {
		v := event.DefaultPlatformTimestamp
		_c.mutation.SetPlatformTimestamp(v)
	}
	if _, ok := _c.mutation.EvidenceMessageIds(); !ok {
		v := event.DefaultEvidenceMessageIds
		_c.mutation.SetEvidenceMessageIds(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := event.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := event.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := event.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventCreate) check() error {
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "Event.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := event.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Event.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Event.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := event.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Event.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Event.description"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := event.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Event.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FromName(); !ok {
		return &ValidationError{Name: "from_name", err: errors.New(`ent: missing required field "Event.from_name"`)}
	}
	if v, ok := _c.mutation.FromName(); ok {
		if err := event.FromNameValidator(v); err != nil {
			return &ValidationError{Name: "from_name", err: fmt.Errorf(`ent: validator failed for field "Event.from_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InChatID(); !ok {
		return &ValidationError{Name: "in_chat_id", err: errors.New(`ent: missing required field "Event.in_chat_id"`)}
	}
	if v, ok := _c.mutation.InChatID(); ok {
		if err := event.InChatIDValidator(v); err != nil {
			return &ValidationError{Name: "in_chat_id", err: fmt.Errorf(`ent: validator failed for field "Event.in_chat_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InChatType(); !ok {
		return &ValidationError{Name: "in_chat_type", err: errors.New(`ent: missing required field "Event.in_chat_type"`)}
	}
	if v, ok := _c.mutation.InChatType(); ok {
		if err := event.InChatTypeValidator(v); err != nil {
			return &ValidationError{Name: "in_chat_type", err: fmt.Errorf(`ent: validator failed for field "Event.in_chat_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlatformTimestamp(); !ok {
		return &ValidationError{Name: "platform_timestamp", err: errors.New(`ent: missing required field "Event.platform_timestamp"`)}
	}
	if _, ok := _c.mutation.EvidenceMessageIds(); !ok {
		return &ValidationError{Name: "evidence_message_ids", err: errors.New(`ent: missing required field "Event.evidence_message_ids"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Event.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Event.updated_at"`)}
	}
	return nil
}

func (_c *EventCreate) sqlSave(ctx context.Context) (*Event, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventCreate) createSpec() (*Event, *sqlgraph.CreateSpec) {
	var (
		_node = &Event{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(event.Table, sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID))
	)
	_spec.Schema = _c.schemaConfig.Event
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(event.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(event.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(event.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(event.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.FromName(); ok {
		_spec.SetField(event.FieldFromName, field.TypeString, value)
		_node.FromName = value
	}
	if value, ok := _c.mutation.InChatID(); ok {
		_spec.SetField(event.FieldInChatID, field.TypeString, value)
		_node.InChatID = value
	}
	if value, ok := _c.mutation.InChatType(); ok {
		_spec.SetField(event.FieldInChatType, field.TypeString, value)
		_node.InChatType = value
	}
	if value, ok := _c.mutation.PlatformTimestamp(); ok {
		_spec.SetField(event.FieldPlatformTimestamp, field.TypeInt64, value)
		_node.PlatformTimestamp = value
	}
	if value, ok := _c.mutation.EvidenceMessageIds(); ok {
		_spec.SetField(event.FieldEvidenceMessageIds, field.TypeJSON, value)
		_node.EvidenceMessageIds = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(event.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(event.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.IdentitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   event.IdentitiesTable,
			Columns: event.IdentitiesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(identity.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.IdentityEvents
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Event.Create().
//		SetPlatform(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EventUpsert) {
//			SetPlatform(v+v).
//		}).
//		Exec(ctx)
func (_c *EventCreate) OnConflict(opts ...sql.ConflictOption) *EventUpsertOne {
	_c.conflict = opts
	return &EventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EventCreate) OnConflictColumns(columns ...string) *EventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EventUpsertOne{
		create: _c,
	}
}

type (
	// EventUpsertOne is the builder for "upsert"-ing
	//  one Event node.
	EventUpsertOne struct {
		create *EventCreate
	}

	// EventUpsert is the "OnConflict" setter.
	EventUpsert struct {
		*sql.UpdateSet
	}
)

// SetPlatform sets the "platform" field.
func (u *EventUpsert) SetPlatform(v string) *EventUpsert {
	u.Set(event.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *EventUpsert) UpdatePlatform() *EventUpsert {
	u.SetExcluded(event.FieldPlatform)
	return u
}

// SetName sets the "name" field.
func (u *EventUpsert) SetName(v string) *EventUpsert {
	u.Set(event.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EventUpsert) UpdateName() *EventUpsert {
	u.SetExcluded(event.FieldName)
	return u
}

// SetTags sets the "tags" field.
func (u *EventUpsert) SetTags(v []string) *EventUpsert {
	u.Set(event.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *EventUpsert) UpdateTags() *EventUpsert {
	u.SetExcluded(event.FieldTags)
	return u
}

// ClearTags clears the value of the "tags" field.
func (u *EventUpsert) ClearTags() *EventUpsert {
	u.SetNull(event.FieldTags)
	return u
}

// SetDescription sets the "description" field.
func (u *EventUpsert) SetDescription(v string) *EventUpsert {
	u.Set(event.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *EventUpsert) UpdateDescription() *EventUpsert {
	u.SetExcluded(event.FieldDescription)
	return u
}

// SetFromName sets the "from_name" field.
func (u *EventUpsert) SetFromName(v string) *EventUpsert {
	u.Set(event.FieldFromName, v)
	return u
}

// UpdateFromName sets the "from_name" field to the value that was provided on create.
func (u *EventUpsert) UpdateFromName() *EventUpsert {
	u.SetExcluded(event.FieldFromName)
	return u
}

// SetInChatID sets the "in_chat_id" field.
func (u *EventUpsert) SetInChatID(v string) *EventUpsert {
	u.Set(event.FieldInChatID, v)
	return u
}

// UpdateInChatID sets the "in_chat_id" field to the value that was provided on create.
func (u *EventUpsert) UpdateInChatID() *EventUpsert {
	u.SetExcluded(event.FieldInChatID)
	return u
}

// SetInChatType sets the "in_chat_type" field.
func (u *EventUpsert) SetInChatType(v string) *EventUpsert {
	u.Set(event.FieldInChatType, v)
	return u
}

// UpdateInChatType sets the "in_chat_type" field to the value that was provided on create.
func (u *EventUpsert) UpdateInChatType() *EventUpsert {
	u.SetExcluded(event.FieldInChatType)
	return u
}

// SetPlatformTimestamp sets the "platform_timestamp" field.
func (u *EventUpsert) SetPlatformTimestamp(v int64) *EventUpsert {
	u.Set(event.FieldPlatformTimestamp, v)
	return u
}

// UpdatePlatformTimestamp sets the "platform_timestamp" field to the value that was provided on create.
func (u *EventUpsert) UpdatePlatformTimestamp() *EventUpsert {
	u.SetExcluded(event.FieldPlatformTimestamp)
	return u
}

// AddPlatformTimestamp adds v to the "platform_timestamp" field.
func (u *EventUpsert) AddPlatformTimestamp(v int64) *EventUpsert {
	u.Add(event.FieldPlatformTimestamp, v)
	return u
}

// SetEvidenceMessageIds sets the "evidence_message_ids" field.
func (u *EventUpsert) SetEvidenceMessageIds(v []uuid.UUID) *EventUpsert {
	u.Set(event.FieldEvidenceMessageIds, v)
	return u
}

// UpdateEvidenceMessageIds sets the "evidence_message_ids" field to the value that was provided on create.
func (u *EventUpsert) UpdateEvidenceMessageIds() *EventUpsert {
	u.SetExcluded(event.FieldEvidenceMessageIds)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *EventUpsert) SetCreatedAt(v int64) *EventUpsert {
	u.Set(event.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *EventUpsert) UpdateCreatedAt() *EventUpsert {
	u.SetExcluded(event.FieldCreatedAt)
	return u
}

// AddCreatedAt adds v to the "created_at" field.
func (u *EventUpsert) AddCreatedAt(v int64) *EventUpsert {
	u.Add(event.FieldCreatedAt, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EventUpsert) SetUpdatedAt(v int64) *EventUpsert {
	u.Set(event.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EventUpsert) UpdateUpdatedAt() *EventUpsert {
	u.SetExcluded(event.FieldUpdatedAt)
	return u
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *EventUpsert) AddUpdatedAt(v int64) *EventUpsert {
	u.Add(event.FieldUpdatedAt, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(event.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EventUpsertOne) UpdateNewValues() *EventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(event.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Event.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EventUpsertOne) Ignore() *EventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EventUpsertOne) DoNothing() *EventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EventCreate.OnConflict
// documentation for more info.
func (u *EventUpsertOne) Update(set func(*EventUpsert)) *EventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EventUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlatform sets the "platform" field.
func (u *EventUpsertOne) SetPlatform(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *EventUpsertOne) UpdatePlatform() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdatePlatform()
	})
}

// SetName sets the "name" field.
func (u *EventUpsertOne) SetName(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateName() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateName()
	})
}

// SetTags sets the "tags" field.
func (u *EventUpsertOne) SetTags(v []string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateTags() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *EventUpsertOne) ClearTags() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearTags()
	})
}

// SetDescription sets the "description" field.
func (u *EventUpsertOne) SetDescription(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateDescription() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateDescription()
	})
}

// SetFromName sets the "from_name" field.
func (u *EventUpsertOne) SetFromName(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetFromName(v)
	})
}

// UpdateFromName sets the "from_name" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateFromName() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateFromName()
	})
}

// SetInChatID sets the "in_chat_id" field.
func (u *EventUpsertOne) SetInChatID(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetInChatID(v)
	})
}

// UpdateInChatID sets the "in_chat_id" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateInChatID() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateInChatID()
	})
}

// SetInChatType sets the "in_chat_type" field.
func (u *EventUpsertOne) SetInChatType(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetInChatType(v)
	})
}

// UpdateInChatType sets the "in_chat_type" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateInChatType() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateInChatType()
	})
}

// SetPlatformTimestamp sets the "platform_timestamp" field.
func (u *EventUpsertOne) SetPlatformTimestamp(v int64) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetPlatformTimestamp(v)
	})
}

// AddPlatformTimestamp adds v to the "platform_timestamp" field.
func (u *EventUpsertOne) AddPlatformTimestamp(v int64) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.AddPlatformTimestamp(v)
	})
}

// UpdatePlatformTimestamp sets the "platform_timestamp" field to the value that was provided on create.
func (u *EventUpsertOne) UpdatePlatformTimestamp() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdatePlatformTimestamp()
	})
}

// SetEvidenceMessageIds sets the "evidence_message_ids" field.
func (u *EventUpsertOne) SetEvidenceMessageIds(v []uuid.UUID) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetEvidenceMessageIds(v)
	})
}

// UpdateEvidenceMessageIds sets the "evidence_message_ids" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateEvidenceMessageIds() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateEvidenceMessageIds()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *EventUpsertOne) SetCreatedAt(v int64) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *EventUpsertOne) AddCreatedAt(v int64) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateCreatedAt() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EventUpsertOne) SetUpdatedAt(v int64) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *EventUpsertOne) AddUpdatedAt(v int64) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateUpdatedAt() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EventUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: EventUpsertOne.ID is not supported by MySQL driver. Use EventUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EventUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// EventCreateBulk is the builder for creating many Event entities in bulk.
type EventCreateBulk struct {
	config
	err      error
	builders []*EventCreate
	conflict []sql.ConflictOption
}

// Save creates the Event entities in the database.
func (_c *EventCreateBulk) Save(ctx context.Context) ([]*Event, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Event, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventCreateBulk) SaveX(ctx context.Context) []*Event {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Event.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EventUpsert) {
//			SetPlatform(v+v).
//		}).
//		Exec(ctx)
func (_c *EventCreateBulk) OnConflict(opts ...sql.ConflictOption) *EventUpsertBulk {
	_c.conflict = opts
	return &EventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *EventCreateBulk) OnConflictColumns(columns ...string) *EventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &EventUpsertBulk{
		create: _c,
	}
}

// EventUpsertBulk is the builder for "upsert"-ing
// a bulk of Event nodes.
type EventUpsertBulk struct {
	create *EventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(event.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *EventUpsertBulk) UpdateNewValues() *EventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(event.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EventUpsertBulk) Ignore() *EventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EventUpsertBulk) DoNothing() *EventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EventCreateBulk.OnConflict
// documentation for more info.
func (u *EventUpsertBulk) Update(set func(*EventUpsert)) *EventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EventUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlatform sets the "platform" field.
func (u *EventUpsertBulk) SetPlatform(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdatePlatform() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdatePlatform()
	})
}

// SetName sets the "name" field.
func (u *EventUpsertBulk) SetName(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateName() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateName()
	})
}

// SetTags sets the "tags" field.
func (u *EventUpsertBulk) SetTags(v []string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateTags() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *EventUpsertBulk) ClearTags() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearTags()
	})
}

// SetDescription sets the "description" field.
func (u *EventUpsertBulk) SetDescription(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateDescription() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateDescription()
	})
}

// SetFromName sets the "from_name" field.
func (u *EventUpsertBulk) SetFromName(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetFromName(v)
	})
}

// UpdateFromName sets the "from_name" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateFromName() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateFromName()
	})
}

// SetInChatID sets the "in_chat_id" field.
func (u *EventUpsertBulk) SetInChatID(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetInChatID(v)
	})
}

// UpdateInChatID sets the "in_chat_id" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateInChatID() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateInChatID()
	})
}

// SetInChatType sets the "in_chat_type" field.
func (u *EventUpsertBulk) SetInChatType(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetInChatType(v)
	})
}

// UpdateInChatType sets the "in_chat_type" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateInChatType() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateInChatType()
	})
}

// SetPlatformTimestamp sets the "platform_timestamp" field.
func (u *EventUpsertBulk) SetPlatformTimestamp(v int64) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetPlatformTimestamp(v)
	})
}

// AddPlatformTimestamp adds v to the "platform_timestamp" field.
func (u *EventUpsertBulk) AddPlatformTimestamp(v int64) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.AddPlatformTimestamp(v)
	})
}

// UpdatePlatformTimestamp sets the "platform_timestamp" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdatePlatformTimestamp() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdatePlatformTimestamp()
	})
}

// SetEvidenceMessageIds sets the "evidence_message_ids" field.
func (u *EventUpsertBulk) SetEvidenceMessageIds(v []uuid.UUID) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetEvidenceMessageIds(v)
	})
}

// UpdateEvidenceMessageIds sets the "evidence_message_ids" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateEvidenceMessageIds() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateEvidenceMessageIds()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *EventUpsertBulk) SetCreatedAt(v int64) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *EventUpsertBulk) AddCreatedAt(v int64) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateCreatedAt() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EventUpsertBulk) SetUpdatedAt(v int64) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *EventUpsertBulk) AddUpdatedAt(v int64) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateUpdatedAt() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *EventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
