// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/luoling8192/adk-agent/ent/event"
	"github.com/luoling8192/adk-agent/ent/identity"
)

// IdentityCreate is the builder for creating a Identity entity.
type IdentityCreate struct {
	config
	mutation *IdentityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPlatform sets the "platform" field.
func (_c *IdentityCreate) SetPlatform(v string) *IdentityCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *IdentityCreate) SetNillablePlatform(v *string) *IdentityCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetPlatformUserID sets the "platform_user_id" field.
func (_c *IdentityCreate) SetPlatformUserID(v string) *IdentityCreate {
	_c.mutation.SetPlatformUserID(v)
	return _c
}

// SetNillablePlatformUserID sets the "platform_user_id" field if the given value is not nil.
func (_c *IdentityCreate) SetNillablePlatformUserID(v *string) *IdentityCreate {
	if v != nil {
		_c.SetPlatformUserID(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *IdentityCreate) SetUsername(v string) *IdentityCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *IdentityCreate) SetNillableUsername(v *string) *IdentityCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *IdentityCreate) SetDisplayName(v string) *IdentityCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *IdentityCreate) SetNillableDisplayName(v *string) *IdentityCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetProfilePhotoURL sets the "profile_photo_url" field.
func (_c *IdentityCreate) SetProfilePhotoURL(v string) *IdentityCreate {
	_c.mutation.SetProfilePhotoURL(v)
	return _c
}

// SetNillableProfilePhotoURL sets the "profile_photo_url" field if the given value is not nil.
func (_c *IdentityCreate) SetNillableProfilePhotoURL(v *string) *IdentityCreate {
	if v != nil {
		_c.SetProfilePhotoURL(*v)
	}
	return _c
}

// SetAltIds sets the "alt_ids" field.
func (_c *IdentityCreate) SetAltIds(v []string) *IdentityCreate {
	_c.mutation.SetAltIds(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *IdentityCreate) SetCreatedAt(v int64) *IdentityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IdentityCreate) SetNillableCreatedAt(v *int64) *IdentityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IdentityCreate) SetUpdatedAt(v int64) *IdentityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IdentityCreate) SetNillableUpdatedAt(v *int64) *IdentityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *IdentityCreate) SetID(v uuid.UUID) *IdentityCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *IdentityCreate) SetNillableID(v *uuid.UUID) *IdentityCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_c *IdentityCreate) AddEventIDs(ids ...uuid.UUID) *IdentityCreate {
	_c.mutation.AddEventIDs(ids...)
	return _c
}

// AddEvents adds the "events" edges to the Event entity.
func (_c *IdentityCreate) AddEvents(v ...*Event) *IdentityCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEventIDs(ids...)
}

// Mutation returns the IdentityMutation object of the builder.
func (_c *IdentityCreate) Mutation() *IdentityMutation {
	return _c.mutation
}

// Save creates the Identity in the database.
func (_c *IdentityCreate) Save(ctx context.Context) (*Identity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IdentityCreate) SaveX(ctx context.Context) *Identity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdentityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdentityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IdentityCreate) defaults() {
	if _, ok := _c.mutation.Platform(); !ok {
		v := identity.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.PlatformUserID(); !ok {
		v := identity.DefaultPlatformUserID
		_c.mutation.SetPlatformUserID(v)
	}
	if _, ok := _c.mutation.Username(); !ok {
		v := identity.DefaultUsername
		_c.mutation.SetUsername(v)
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		v := identity.DefaultDisplayName
		_c.mutation.SetDisplayName(v)
	}
	if _, ok := _c.mutation.ProfilePhotoURL(); !ok {
		v := identity.DefaultProfilePhotoURL
		_c.mutation.SetProfilePhotoURL(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := identity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := identity.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := identity.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IdentityCreate) check() error {
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "Identity.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := identity.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Identity.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlatformUserID(); !ok {
		return &ValidationError{Name: "platform_user_id", err: errors.New(`ent: missing required field "Identity.platform_user_id"`)}
	}
	if v, ok := _c.mutation.PlatformUserID(); ok {
		if err := identity.PlatformUserIDValidator(v); err != nil {
			return &ValidationError{Name: "platform_user_id", err: fmt.Errorf(`ent: validator failed for field "Identity.platform_user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "Identity.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := identity.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Identity.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "Identity.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := identity.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Identity.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProfilePhotoURL(); !ok {
		return &ValidationError{Name: "profile_photo_url", err: errors.New(`ent: missing required field "Identity.profile_photo_url"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Identity.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Identity.updated_at"`)}
	}
	return nil
}

func (_c *IdentityCreate) sqlSave(ctx context.Context) (*Identity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IdentityCreate) createSpec() (*Identity, *sqlgraph.CreateSpec) {
	var (
		_node = &Identity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(identity.Table, sqlgraph.NewFieldSpec(identity.FieldID, field.TypeUUID))
	)
	_spec.Schema = _c.schemaConfig.Identity
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(identity.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.PlatformUserID(); ok {
		_spec.SetField(identity.FieldPlatformUserID, field.TypeString, value)
		_node.PlatformUserID = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(identity.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(identity.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.ProfilePhotoURL(); ok {
		_spec.SetField(identity.FieldProfilePhotoURL, field.TypeString, value)
		_node.ProfilePhotoURL = value
	}
	if value, ok := _c.mutation.AltIds(); ok {
		_spec.SetField(identity.FieldAltIds, field.TypeJSON, value)
		_node.AltIds = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(identity.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(identity.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   identity.EventsTable,
			Columns: identity.EventsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _c.schemaConfig.IdentityEvents
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Identity.Create().
//		SetPlatform(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IdentityUpsert) {
//			SetPlatform(v+v).
//		}).
//		Exec(ctx)
func (_c *IdentityCreate) OnConflict(opts ...sql.ConflictOption) *IdentityUpsertOne {
	_c.conflict = opts
	return &IdentityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Identity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IdentityCreate) OnConflictColumns(columns ...string) *IdentityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IdentityUpsertOne{
		create: _c,
	}
}

type (
	// IdentityUpsertOne is the builder for "upsert"-ing
	//  one Identity node.
	IdentityUpsertOne struct {
		create *IdentityCreate
	}

	// IdentityUpsert is the "OnConflict" setter.
	IdentityUpsert struct {
		*sql.UpdateSet
	}
)

// SetPlatform sets the "platform" field.
func (u *IdentityUpsert) SetPlatform(v string) *IdentityUpsert {
	u.Set(identity.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *IdentityUpsert) UpdatePlatform() *IdentityUpsert {
	u.SetExcluded(identity.FieldPlatform)
	return u
}

// SetPlatformUserID sets the "platform_user_id" field.
func (u *IdentityUpsert) SetPlatformUserID(v string) *IdentityUpsert {
	u.Set(identity.FieldPlatformUserID, v)
	return u
}

// UpdatePlatformUserID sets the "platform_user_id" field to the value that was provided on create.
func (u *IdentityUpsert) UpdatePlatformUserID() *IdentityUpsert {
	u.SetExcluded(identity.FieldPlatformUserID)
	return u
}

// SetUsername sets the "username" field.
func (u *IdentityUpsert) SetUsername(v string) *IdentityUpsert {
	u.Set(identity.FieldUsername, v)
	return u
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *IdentityUpsert) UpdateUsername() *IdentityUpsert {
	u.SetExcluded(identity.FieldUsername)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *IdentityUpsert) SetDisplayName(v string) *IdentityUpsert {
	u.Set(identity.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *IdentityUpsert) UpdateDisplayName() *IdentityUpsert {
	u.SetExcluded(identity.FieldDisplayName)
	return u
}

// SetProfilePhotoURL sets the "profile_photo_url" field.
func (u *IdentityUpsert) SetProfilePhotoURL(v string) *IdentityUpsert {
	u.Set(identity.FieldProfilePhotoURL, v)
	return u
}

// UpdateProfilePhotoURL sets the "profile_photo_url" field to the value that was provided on create.
func (u *IdentityUpsert) UpdateProfilePhotoURL() *IdentityUpsert {
	u.SetExcluded(identity.FieldProfilePhotoURL)
	return u
}

// SetAltIds sets the "alt_ids" field.
func (u *IdentityUpsert) SetAltIds(v []string) *IdentityUpsert {
	u.Set(identity.FieldAltIds, v)
	return u
}

// UpdateAltIds sets the "alt_ids" field to the value that was provided on create.
func (u *IdentityUpsert) UpdateAltIds() *IdentityUpsert {
	u.SetExcluded(identity.FieldAltIds)
	return u
}

// ClearAltIds clears the value of the "alt_ids" field.
func (u *IdentityUpsert) ClearAltIds() *IdentityUpsert {
	u.SetNull(identity.FieldAltIds)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *IdentityUpsert) SetCreatedAt(v int64) *IdentityUpsert {
	u.Set(identity.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *IdentityUpsert) UpdateCreatedAt() *IdentityUpsert {
	u.SetExcluded(identity.FieldCreatedAt)
	return u
}

// AddCreatedAt adds v to the "created_at" field.
func (u *IdentityUpsert) AddCreatedAt(v int64) *IdentityUpsert {
	u.Add(identity.FieldCreatedAt, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IdentityUpsert) SetUpdatedAt(v int64) *IdentityUpsert {
	u.Set(identity.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IdentityUpsert) UpdateUpdatedAt() *IdentityUpsert {
	u.SetExcluded(identity.FieldUpdatedAt)
	return u
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *IdentityUpsert) AddUpdatedAt(v int64) *IdentityUpsert {
	u.Add(identity.FieldUpdatedAt, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Identity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(identity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IdentityUpsertOne) UpdateNewValues() *IdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(identity.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Identity.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IdentityUpsertOne) Ignore() *IdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IdentityUpsertOne) DoNothing() *IdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IdentityCreate.OnConflict
// documentation for more info.
func (u *IdentityUpsertOne) Update(set func(*IdentityUpsert)) *IdentityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IdentityUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlatform sets the "platform" field.
func (u *IdentityUpsertOne) SetPlatform(v string) *IdentityUpsertOne {
	return u.Update(func(s *IdentityUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *IdentityUpsertOne) UpdatePlatform() *IdentityUpsertOne {
	return u.Update(func(s *IdentityUpsert) {
		s.UpdatePlatform()
	})
}

// SetPlatformUserID sets the "platform_user_id" field.
func (u *IdentityUpsertOne) SetPlatformUserID(v string) *IdentityUpsertOne {
	return u.Update(func(s *IdentityUpsert) {
		s.SetPlatformUserID(v)
	})
}

// UpdatePlatformUserID sets the "platform_user_id" field to the value that was provided on create.
func (u *IdentityUpsertOne) UpdatePlatformUserID() *IdentityUpsertOne {
	return u.Update(func(s *IdentityUpsert) {
		s.UpdatePlatformUserID()
	})
}

// SetUsername sets the "username" field.
func (u *IdentityUpsertOne) SetUsername(v string) *IdentityUpsertOne {
	return u.Update(func(s *IdentityUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *IdentityUpsertOne) UpdateUsername() *IdentityUpsertOne {
	return u.Update(func(s *IdentityUpsert) {
		s.UpdateUsername()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *IdentityUpsertOne) SetDisplayName(v string) *IdentityUpsertOne {
	return u.Update(func(s *IdentityUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *IdentityUpsertOne) UpdateDisplayName() *IdentityUpsertOne {
	return u.Update(func(s *IdentityUpsert) {
		s.UpdateDisplayName()
	})
}

// SetProfilePhotoURL sets the "profile_photo_url" field.
func (u *IdentityUpsertOne) SetProfilePhotoURL(v string) *IdentityUpsertOne {
	return u.Update(func(s *IdentityUpsert) {
		s.SetProfilePhotoURL(v)
	})
}

// UpdateProfilePhotoURL sets the "profile_photo_url" field to the value that was provided on create.
func (u *IdentityUpsertOne) UpdateProfilePhotoURL() *IdentityUpsertOne {
	return u.Update(func(s *IdentityUpsert) {
		s.UpdateProfilePhotoURL()
	})
}

// SetAltIds sets the "alt_ids" field.
func (u *IdentityUpsertOne) SetAltIds(v []string) *IdentityUpsertOne {
	return u.Update(func(s *IdentityUpsert) {
		s.SetAltIds(v)
	})
}

// UpdateAltIds sets the "alt_ids" field to the value that was provided on create.
func (u *IdentityUpsertOne) UpdateAltIds() *IdentityUpsertOne {
	return u.Update(func(s *IdentityUpsert) {
		s.UpdateAltIds()
	})
}

// ClearAltIds clears the value of the "alt_ids" field.
func (u *IdentityUpsertOne) ClearAltIds() *IdentityUpsertOne {
	return u.Update(func(s *IdentityUpsert) {
		s.ClearAltIds()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *IdentityUpsertOne) SetCreatedAt(v int64) *IdentityUpsertOne {
	return u.Update(func(s *IdentityUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *IdentityUpsertOne) AddCreatedAt(v int64) *IdentityUpsertOne {
	return u.Update(func(s *IdentityUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *IdentityUpsertOne) UpdateCreatedAt() *IdentityUpsertOne {
	return u.Update(func(s *IdentityUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IdentityUpsertOne) SetUpdatedAt(v int64) *IdentityUpsertOne {
	return u.Update(func(s *IdentityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *IdentityUpsertOne) AddUpdatedAt(v int64) *IdentityUpsertOne {
	return u.Update(func(s *IdentityUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IdentityUpsertOne) UpdateUpdatedAt() *IdentityUpsertOne {
	return u.Update(func(s *IdentityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *IdentityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IdentityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IdentityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IdentityUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: IdentityUpsertOne.ID is not supported by MySQL driver. Use IdentityUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IdentityUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IdentityCreateBulk is the builder for creating many Identity entities in bulk.
type IdentityCreateBulk struct {
	config
	err      error
	builders []*IdentityCreate
	conflict []sql.ConflictOption
}

// Save creates the Identity entities in the database.
func (_c *IdentityCreateBulk) Save(ctx context.Context) ([]*Identity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Identity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IdentityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IdentityCreateBulk) SaveX(ctx context.Context) []*Identity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdentityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdentityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Identity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IdentityUpsert) {
//			SetPlatform(v+v).
//		}).
//		Exec(ctx)
func (_c *IdentityCreateBulk) OnConflict(opts ...sql.ConflictOption) *IdentityUpsertBulk {
	_c.conflict = opts
	return &IdentityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Identity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IdentityCreateBulk) OnConflictColumns(columns ...string) *IdentityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IdentityUpsertBulk{
		create: _c,
	}
}

// IdentityUpsertBulk is the builder for "upsert"-ing
// a bulk of Identity nodes.
type IdentityUpsertBulk struct {
	create *IdentityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Identity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(identity.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IdentityUpsertBulk) UpdateNewValues() *IdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(identity.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Identity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IdentityUpsertBulk) Ignore() *IdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IdentityUpsertBulk) DoNothing() *IdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IdentityCreateBulk.OnConflict
// documentation for more info.
func (u *IdentityUpsertBulk) Update(set func(*IdentityUpsert)) *IdentityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IdentityUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlatform sets the "platform" field.
func (u *IdentityUpsertBulk) SetPlatform(v string) *IdentityUpsertBulk {
	return u.Update(func(s *IdentityUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *IdentityUpsertBulk) UpdatePlatform() *IdentityUpsertBulk {
	return u.Update(func(s *IdentityUpsert) {
		s.UpdatePlatform()
	})
}

// SetPlatformUserID sets the "platform_user_id" field.
func (u *IdentityUpsertBulk) SetPlatformUserID(v string) *IdentityUpsertBulk {
	return u.Update(func(s *IdentityUpsert) {
		s.SetPlatformUserID(v)
	})
}

// UpdatePlatformUserID sets the "platform_user_id" field to the value that was provided on create.
func (u *IdentityUpsertBulk) UpdatePlatformUserID() *IdentityUpsertBulk {
	return u.Update(func(s *IdentityUpsert) {
		s.UpdatePlatformUserID()
	})
}

// SetUsername sets the "username" field.
func (u *IdentityUpsertBulk) SetUsername(v string) *IdentityUpsertBulk {
	return u.Update(func(s *IdentityUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *IdentityUpsertBulk) UpdateUsername() *IdentityUpsertBulk {
	return u.Update(func(s *IdentityUpsert) {
		s.UpdateUsername()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *IdentityUpsertBulk) SetDisplayName(v string) *IdentityUpsertBulk {
	return u.Update(func(s *IdentityUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *IdentityUpsertBulk) UpdateDisplayName() *IdentityUpsertBulk {
	return u.Update(func(s *IdentityUpsert) {
		s.UpdateDisplayName()
	})
}

// SetProfilePhotoURL sets the "profile_photo_url" field.
func (u *IdentityUpsertBulk) SetProfilePhotoURL(v string) *IdentityUpsertBulk {
	return u.Update(func(s *IdentityUpsert) {
		s.SetProfilePhotoURL(v)
	})
}

// UpdateProfilePhotoURL sets the "profile_photo_url" field to the value that was provided on create.
func (u *IdentityUpsertBulk) UpdateProfilePhotoURL() *IdentityUpsertBulk {
	return u.Update(func(s *IdentityUpsert) {
		s.UpdateProfilePhotoURL()
	})
}

// SetAltIds sets the "alt_ids" field.
func (u *IdentityUpsertBulk) SetAltIds(v []string) *IdentityUpsertBulk {
	return u.Update(func(s *IdentityUpsert) {
		s.SetAltIds(v)
	})
}

// UpdateAltIds sets the "alt_ids" field to the value that was provided on create.
func (u *IdentityUpsertBulk) UpdateAltIds() *IdentityUpsertBulk {
	return u.Update(func(s *IdentityUpsert) {
		s.UpdateAltIds()
	})
}

// ClearAltIds clears the value of the "alt_ids" field.
func (u *IdentityUpsertBulk) ClearAltIds() *IdentityUpsertBulk {
	return u.Update(func(s *IdentityUpsert) {
		s.ClearAltIds()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *IdentityUpsertBulk) SetCreatedAt(v int64) *IdentityUpsertBulk {
	return u.Update(func(s *IdentityUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *IdentityUpsertBulk) AddCreatedAt(v int64) *IdentityUpsertBulk {
	return u.Update(func(s *IdentityUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *IdentityUpsertBulk) UpdateCreatedAt() *IdentityUpsertBulk {
	return u.Update(func(s *IdentityUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *IdentityUpsertBulk) SetUpdatedAt(v int64) *IdentityUpsertBulk {
	return u.Update(func(s *IdentityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *IdentityUpsertBulk) AddUpdatedAt(v int64) *IdentityUpsertBulk {
	return u.Update(func(s *IdentityUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *IdentityUpsertBulk) UpdateUpdatedAt() *IdentityUpsertBulk {
	return u.Update(func(s *IdentityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *IdentityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IdentityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IdentityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IdentityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
