// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/luoling8192/adk-agent/ent/event"
	"github.com/luoling8192/adk-agent/ent/identity"
	"github.com/luoling8192/adk-agent/ent/internal"
	"github.com/luoling8192/adk-agent/ent/predicate"
)

// IdentityUpdate is the builder for updating Identity entities.
type IdentityUpdate struct {
	config
	hooks    []Hook
	mutation *IdentityMutation
}

// Where appends a list predicates to the IdentityUpdate builder.
func (_u *IdentityUpdate) Where(ps ...predicate.Identity) *IdentityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *IdentityUpdate) SetPlatform(v string) *IdentityUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *IdentityUpdate) SetNillablePlatform(v *string) *IdentityUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetPlatformUserID sets the "platform_user_id" field.
func (_u *IdentityUpdate) SetPlatformUserID(v string) *IdentityUpdate {
	_u.mutation.SetPlatformUserID(v)
	return _u
}

// SetNillablePlatformUserID sets the "platform_user_id" field if the given value is not nil.
func (_u *IdentityUpdate) SetNillablePlatformUserID(v *string) *IdentityUpdate {
	if v != nil {
		_u.SetPlatformUserID(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *IdentityUpdate) SetUsername(v string) *IdentityUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *IdentityUpdate) SetNillableUsername(v *string) *IdentityUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *IdentityUpdate) SetDisplayName(v string) *IdentityUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *IdentityUpdate) SetNillableDisplayName(v *string) *IdentityUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetProfilePhotoURL sets the "profile_photo_url" field.
func (_u *IdentityUpdate) SetProfilePhotoURL(v string) *IdentityUpdate {
	_u.mutation.SetProfilePhotoURL(v)
	return _u
}

// SetNillableProfilePhotoURL sets the "profile_photo_url" field if the given value is not nil.
func (_u *IdentityUpdate) SetNillableProfilePhotoURL(v *string) *IdentityUpdate {
	if v != nil {
		_u.SetProfilePhotoURL(*v)
	}
	return _u
}

// SetAltIds sets the "alt_ids" field.
func (_u *IdentityUpdate) SetAltIds(v []string) *IdentityUpdate {
	_u.mutation.SetAltIds(v)
	return _u
}

// AppendAltIds appends value to the "alt_ids" field.
func (_u *IdentityUpdate) AppendAltIds(v []string) *IdentityUpdate {
	_u.mutation.AppendAltIds(v)
	return _u
}

// ClearAltIds clears the value of the "alt_ids" field.
func (_u *IdentityUpdate) ClearAltIds() *IdentityUpdate {
	_u.mutation.ClearAltIds()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *IdentityUpdate) SetCreatedAt(v int64) *IdentityUpdate {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *IdentityUpdate) SetNillableCreatedAt(v *int64) *IdentityUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *IdentityUpdate) AddCreatedAt(v int64) *IdentityUpdate {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IdentityUpdate) SetUpdatedAt(v int64) *IdentityUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *IdentityUpdate) AddUpdatedAt(v int64) *IdentityUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_u *IdentityUpdate) AddEventIDs(ids ...uuid.UUID) *IdentityUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the Event entity.
func (_u *IdentityUpdate) AddEvents(v ...*Event) *IdentityUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the IdentityMutation object of the builder.
func (_u *IdentityUpdate) Mutation() *IdentityMutation {
	return _u.mutation
}

// ClearEvents clears all "events" edges to the Event entity.
func (_u *IdentityUpdate) ClearEvents() *IdentityUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to Event entities by IDs.
func (_u *IdentityUpdate) RemoveEventIDs(ids ...uuid.UUID) *IdentityUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to Event entities.
func (_u *IdentityUpdate) RemoveEvents(v ...*Event) *IdentityUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IdentityUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IdentityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IdentityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IdentityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IdentityUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := identity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *IdentityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(identity.Table, identity.Columns, sqlgraph.NewFieldSpec(identity.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(identity.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformUserID(); ok {
		_spec.SetField(identity.FieldPlatformUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(identity.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(identity.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProfilePhotoURL(); ok {
		_spec.SetField(identity.FieldProfilePhotoURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.AltIds(); ok {
		_spec.SetField(identity.FieldAltIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAltIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, identity.FieldAltIds, value)
		})
	}
	if _u.mutation.AltIdsCleared() {
		_spec.ClearField(identity.FieldAltIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(identity.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(identity.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(identity.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(identity.FieldUpdatedAt, field.TypeInt64, value)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   identity.EventsTable,
			Columns: identity.EventsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.IdentityEvents
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   identity.EventsTable,
			Columns: identity.EventsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.IdentityEvents
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   identity.EventsTable,
			Columns: identity.EventsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.IdentityEvents
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Identity
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{identity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IdentityUpdateOne is the builder for updating a single Identity entity.
type IdentityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IdentityMutation
}

// SetPlatform sets the "platform" field.
func (_u *IdentityUpdateOne) SetPlatform(v string) *IdentityUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *IdentityUpdateOne) SetNillablePlatform(v *string) *IdentityUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetPlatformUserID sets the "platform_user_id" field.
func (_u *IdentityUpdateOne) SetPlatformUserID(v string) *IdentityUpdateOne {
	_u.mutation.SetPlatformUserID(v)
	return _u
}

// SetNillablePlatformUserID sets the "platform_user_id" field if the given value is not nil.
func (_u *IdentityUpdateOne) SetNillablePlatformUserID(v *string) *IdentityUpdateOne {
	if v != nil {
		_u.SetPlatformUserID(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *IdentityUpdateOne) SetUsername(v string) *IdentityUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *IdentityUpdateOne) SetNillableUsername(v *string) *IdentityUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *IdentityUpdateOne) SetDisplayName(v string) *IdentityUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *IdentityUpdateOne) SetNillableDisplayName(v *string) *IdentityUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetProfilePhotoURL sets the "profile_photo_url" field.
func (_u *IdentityUpdateOne) SetProfilePhotoURL(v string) *IdentityUpdateOne {
	_u.mutation.SetProfilePhotoURL(v)
	return _u
}

// SetNillableProfilePhotoURL sets the "profile_photo_url" field if the given value is not nil.
func (_u *IdentityUpdateOne) SetNillableProfilePhotoURL(v *string) *IdentityUpdateOne {
	if v != nil {
		_u.SetProfilePhotoURL(*v)
	}
	return _u
}

// SetAltIds sets the "alt_ids" field.
func (_u *IdentityUpdateOne) SetAltIds(v []string) *IdentityUpdateOne {
	_u.mutation.SetAltIds(v)
	return _u
}

// AppendAltIds appends value to the "alt_ids" field.
func (_u *IdentityUpdateOne) AppendAltIds(v []string) *IdentityUpdateOne {
	_u.mutation.AppendAltIds(v)
	return _u
}

// ClearAltIds clears the value of the "alt_ids" field.
func (_u *IdentityUpdateOne) ClearAltIds() *IdentityUpdateOne {
	_u.mutation.ClearAltIds()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *IdentityUpdateOne) SetCreatedAt(v int64) *IdentityUpdateOne {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *IdentityUpdateOne) SetNillableCreatedAt(v *int64) *IdentityUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *IdentityUpdateOne) AddCreatedAt(v int64) *IdentityUpdateOne {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IdentityUpdateOne) SetUpdatedAt(v int64) *IdentityUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *IdentityUpdateOne) AddUpdatedAt(v int64) *IdentityUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_u *IdentityUpdateOne) AddEventIDs(ids ...uuid.UUID) *IdentityUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the Event entity.
func (_u *IdentityUpdateOne) AddEvents(v ...*Event) *IdentityUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the IdentityMutation object of the builder.
func (_u *IdentityUpdateOne) Mutation() *IdentityMutation {
	return _u.mutation
}

// ClearEvents clears all "events" edges to the Event entity.
func (_u *IdentityUpdateOne) ClearEvents() *IdentityUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to Event entities by IDs.
func (_u *IdentityUpdateOne) RemoveEventIDs(ids ...uuid.UUID) *IdentityUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to Event entities.
func (_u *IdentityUpdateOne) RemoveEvents(v ...*Event) *IdentityUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Where appends a list predicates to the IdentityUpdate builder.
func (_u *IdentityUpdateOne) Where(ps ...predicate.Identity) *IdentityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IdentityUpdateOne) Select(field string, fields ...string) *IdentityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Identity entity.
func (_u *IdentityUpdateOne) Save(ctx context.Context) (*Identity, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IdentityUpdateOne) SaveX(ctx context.Context) *Identity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IdentityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IdentityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IdentityUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := identity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *IdentityUpdateOne) sqlSave(ctx context.Context) (_node *Identity, err error) {
	_spec := sqlgraph.NewUpdateSpec(identity.Table, identity.Columns, sqlgraph.NewFieldSpec(identity.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Identity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, identity.FieldID)
		for _, f := range fields {
			if !identity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != identity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(identity.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlatformUserID(); ok {
		_spec.SetField(identity.FieldPlatformUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(identity.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(identity.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProfilePhotoURL(); ok {
		_spec.SetField(identity.FieldProfilePhotoURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.AltIds(); ok {
		_spec.SetField(identity.FieldAltIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAltIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, identity.FieldAltIds, value)
		})
	}
	if _u.mutation.AltIdsCleared() {
		_spec.ClearField(identity.FieldAltIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(identity.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(identity.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(identity.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(identity.FieldUpdatedAt, field.TypeInt64, value)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   identity.EventsTable,
			Columns: identity.EventsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.IdentityEvents
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   identity.EventsTable,
			Columns: identity.EventsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.IdentityEvents
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   identity.EventsTable,
			Columns: identity.EventsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		edge.Schema = _u.schemaConfig.IdentityEvents
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = _u.schemaConfig.Identity
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &Identity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{identity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
