// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/luoling8192/mindwave/ent/internal"
	"github.com/luoling8192/mindwave/ent/joinedchat"
	"github.com/luoling8192/mindwave/ent/predicate"
)

// JoinedChatDelete is the builder for deleting a JoinedChat entity.
type JoinedChatDelete struct {
	config
	hooks    []Hook
	mutation *JoinedChatMutation
}

// Where appends a list predicates to the JoinedChatDelete builder.
func (_d *JoinedChatDelete) Where(ps ...predicate.JoinedChat) *JoinedChatDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *JoinedChatDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *JoinedChatDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *JoinedChatDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(joinedchat.Table, sqlgraph.NewFieldSpec(joinedchat.FieldID, field.TypeUUID))
	_spec.Node.Schema = _d.schemaConfig.JoinedChat
	ctx = internal.NewSchemaConfigContext(ctx, _d.schemaConfig)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// JoinedChatDeleteOne is the builder for deleting a single JoinedChat entity.
type JoinedChatDeleteOne struct {
	_d *JoinedChatDelete
}

// Where appends a list predicates to the JoinedChatDelete builder.
func (_d *JoinedChatDeleteOne) Where(ps ...predicate.JoinedChat) *JoinedChatDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *JoinedChatDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{joinedchat.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *JoinedChatDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
