// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/luoling8192/mindwave/ent/internal"
	"github.com/luoling8192/mindwave/ent/joinedchat"
	"github.com/luoling8192/mindwave/ent/predicate"
)

// JoinedChatUpdate is the builder for updating JoinedChat entities.
type JoinedChatUpdate struct {
	config
	hooks    []Hook
	mutation *JoinedChatMutation
}

// Where appends a list predicates to the JoinedChatUpdate builder.
func (_u *JoinedChatUpdate) Where(ps ...predicate.JoinedChat) *JoinedChatUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *JoinedChatUpdate) SetPlatform(v string) *JoinedChatUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *JoinedChatUpdate) SetNillablePlatform(v *string) *JoinedChatUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *JoinedChatUpdate) SetChatID(v string) *JoinedChatUpdate {
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *JoinedChatUpdate) SetNillableChatID(v *string) *JoinedChatUpdate {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// SetChatName sets the "chat_name" field.
func (_u *JoinedChatUpdate) SetChatName(v string) *JoinedChatUpdate {
	_u.mutation.SetChatName(v)
	return _u
}

// SetNillableChatName sets the "chat_name" field if the given value is not nil.
func (_u *JoinedChatUpdate) SetNillableChatName(v *string) *JoinedChatUpdate {
	if v != nil {
		_u.SetChatName(*v)
	}
	return _u
}

// SetChatType sets the "chat_type" field.
func (_u *JoinedChatUpdate) SetChatType(v string) *JoinedChatUpdate {
	_u.mutation.SetChatType(v)
	return _u
}

// SetNillableChatType sets the "chat_type" field if the given value is not nil.
func (_u *JoinedChatUpdate) SetNillableChatType(v *string) *JoinedChatUpdate {
	if v != nil {
		_u.SetChatType(*v)
	}
	return _u
}

// SetDialogDate sets the "dialog_date" field.
func (_u *JoinedChatUpdate) SetDialogDate(v int64) *JoinedChatUpdate {
	_u.mutation.ResetDialogDate()
	_u.mutation.SetDialogDate(v)
	return _u
}

// SetNillableDialogDate sets the "dialog_date" field if the given value is not nil.
func (_u *JoinedChatUpdate) SetNillableDialogDate(v *int64) *JoinedChatUpdate {
	if v != nil {
		_u.SetDialogDate(*v)
	}
	return _u
}

// AddDialogDate adds value to the "dialog_date" field.
func (_u *JoinedChatUpdate) AddDialogDate(v int64) *JoinedChatUpdate {
	_u.mutation.AddDialogDate(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *JoinedChatUpdate) SetCreatedAt(v int64) *JoinedChatUpdate {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *JoinedChatUpdate) SetNillableCreatedAt(v *int64) *JoinedChatUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *JoinedChatUpdate) AddCreatedAt(v int64) *JoinedChatUpdate {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *JoinedChatUpdate) SetUpdatedAt(v int64) *JoinedChatUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *JoinedChatUpdate) AddUpdatedAt(v int64) *JoinedChatUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// Mutation returns the JoinedChatMutation object of the builder.
func (_u *JoinedChatUpdate) Mutation() *JoinedChatMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *JoinedChatUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JoinedChatUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *JoinedChatUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JoinedChatUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *JoinedChatUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := joinedchat.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JoinedChatUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := joinedchat.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "JoinedChat.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChatID(); ok {
		if err := joinedchat.ChatIDValidator(v); err != nil {
			return &ValidationError{Name: "chat_id", err: fmt.Errorf(`ent: validator failed for field "JoinedChat.chat_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChatName(); ok {
		if err := joinedchat.ChatNameValidator(v); err != nil {
			return &ValidationError{Name: "chat_name", err: fmt.Errorf(`ent: validator failed for field "JoinedChat.chat_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChatType(); ok {
		if err := joinedchat.ChatTypeValidator(v); err != nil {
			return &ValidationError{Name: "chat_type", err: fmt.Errorf(`ent: validator failed for field "JoinedChat.chat_type": %w`, err)}
		}
	}
	return nil
}

func (_u *JoinedChatUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(joinedchat.Table, joinedchat.Columns, sqlgraph.NewFieldSpec(joinedchat.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(joinedchat.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(joinedchat.FieldChatID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChatName(); ok {
		_spec.SetField(joinedchat.FieldChatName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChatType(); ok {
		_spec.SetField(joinedchat.FieldChatType, field.TypeString, value)
	}
	if value, ok := _u.mutation.DialogDate(); ok {
		_spec.SetField(joinedchat.FieldDialogDate, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDialogDate(); ok {
		_spec.AddField(joinedchat.FieldDialogDate, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(joinedchat.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(joinedchat.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(joinedchat.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(joinedchat.FieldUpdatedAt, field.TypeInt64, value)
	}
	_spec.Node.Schema = _u.schemaConfig.JoinedChat
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{joinedchat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// JoinedChatUpdateOne is the builder for updating a single JoinedChat entity.
type JoinedChatUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JoinedChatMutation
}

// SetPlatform sets the "platform" field.
func (_u *JoinedChatUpdateOne) SetPlatform(v string) *JoinedChatUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *JoinedChatUpdateOne) SetNillablePlatform(v *string) *JoinedChatUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *JoinedChatUpdateOne) SetChatID(v string) *JoinedChatUpdateOne {
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *JoinedChatUpdateOne) SetNillableChatID(v *string) *JoinedChatUpdateOne {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// SetChatName sets the "chat_name" field.
func (_u *JoinedChatUpdateOne) SetChatName(v string) *JoinedChatUpdateOne {
	_u.mutation.SetChatName(v)
	return _u
}

// SetNillableChatName sets the "chat_name" field if the given value is not nil.
func (_u *JoinedChatUpdateOne) SetNillableChatName(v *string) *JoinedChatUpdateOne {
	if v != nil {
		_u.SetChatName(*v)
	}
	return _u
}

// SetChatType sets the "chat_type" field.
func (_u *JoinedChatUpdateOne) SetChatType(v string) *JoinedChatUpdateOne {
	_u.mutation.SetChatType(v)
	return _u
}

// SetNillableChatType sets the "chat_type" field if the given value is not nil.
func (_u *JoinedChatUpdateOne) SetNillableChatType(v *string) *JoinedChatUpdateOne {
	if v != nil {
		_u.SetChatType(*v)
	}
	return _u
}

// SetDialogDate sets the "dialog_date" field.
func (_u *JoinedChatUpdateOne) SetDialogDate(v int64) *JoinedChatUpdateOne {
	_u.mutation.ResetDialogDate()
	_u.mutation.SetDialogDate(v)
	return _u
}

// SetNillableDialogDate sets the "dialog_date" field if the given value is not nil.
func (_u *JoinedChatUpdateOne) SetNillableDialogDate(v *int64) *JoinedChatUpdateOne {
	if v != nil {
		_u.SetDialogDate(*v)
	}
	return _u
}

// AddDialogDate adds value to the "dialog_date" field.
func (_u *JoinedChatUpdateOne) AddDialogDate(v int64) *JoinedChatUpdateOne {
	_u.mutation.AddDialogDate(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *JoinedChatUpdateOne) SetCreatedAt(v int64) *JoinedChatUpdateOne {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *JoinedChatUpdateOne) SetNillableCreatedAt(v *int64) *JoinedChatUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *JoinedChatUpdateOne) AddCreatedAt(v int64) *JoinedChatUpdateOne {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *JoinedChatUpdateOne) SetUpdatedAt(v int64) *JoinedChatUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *JoinedChatUpdateOne) AddUpdatedAt(v int64) *JoinedChatUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// Mutation returns the JoinedChatMutation object of the builder.
func (_u *JoinedChatUpdateOne) Mutation() *JoinedChatMutation {
	return _u.mutation
}

// Where appends a list predicates to the JoinedChatUpdate builder.
func (_u *JoinedChatUpdateOne) Where(ps ...predicate.JoinedChat) *JoinedChatUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *JoinedChatUpdateOne) Select(field string, fields ...string) *JoinedChatUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated JoinedChat entity.
func (_u *JoinedChatUpdateOne) Save(ctx context.Context) (*JoinedChat, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JoinedChatUpdateOne) SaveX(ctx context.Context) *JoinedChat {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *JoinedChatUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JoinedChatUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *JoinedChatUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := joinedchat.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JoinedChatUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := joinedchat.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "JoinedChat.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChatID(); ok {
		if err := joinedchat.ChatIDValidator(v); err != nil {
			return &ValidationError{Name: "chat_id", err: fmt.Errorf(`ent: validator failed for field "JoinedChat.chat_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChatName(); ok {
		if err := joinedchat.ChatNameValidator(v); err != nil {
			return &ValidationError{Name: "chat_name", err: fmt.Errorf(`ent: validator failed for field "JoinedChat.chat_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChatType(); ok {
		if err := joinedchat.ChatTypeValidator(v); err != nil {
			return &ValidationError{Name: "chat_type", err: fmt.Errorf(`ent: validator failed for field "JoinedChat.chat_type": %w`, err)}
		}
	}
	return nil
}

func (_u *JoinedChatUpdateOne) sqlSave(ctx context.Context) (_node *JoinedChat, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(joinedchat.Table, joinedchat.Columns, sqlgraph.NewFieldSpec(joinedchat.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "JoinedChat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, joinedchat.FieldID)
		for _, f := range fields {
			if !joinedchat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != joinedchat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(joinedchat.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(joinedchat.FieldChatID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChatName(); ok {
		_spec.SetField(joinedchat.FieldChatName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChatType(); ok {
		_spec.SetField(joinedchat.FieldChatType, field.TypeString, value)
	}
	if value, ok := _u.mutation.DialogDate(); ok {
		_spec.SetField(joinedchat.FieldDialogDate, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDialogDate(); ok {
		_spec.AddField(joinedchat.FieldDialogDate, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(joinedchat.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(joinedchat.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(joinedchat.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(joinedchat.FieldUpdatedAt, field.TypeInt64, value)
	}
	_spec.Node.Schema = _u.schemaConfig.JoinedChat
	ctx = internal.NewSchemaConfigContext(ctx, _u.schemaConfig)
	_node = &JoinedChat{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{joinedchat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
