// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/luoling8192/adk-agent/ent/chatmessage"
	"github.com/luoling8192/adk-agent/ent/event"
	"github.com/luoling8192/adk-agent/ent/identity"
	"github.com/luoling8192/adk-agent/ent/joinedchat"
	"github.com/luoling8192/adk-agent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chatmessageFields := schema.ChatMessage{}.Fields()
	_ = chatmessageFields
	// chatmessageDescPlatform is the schema descriptor for platform field.
	chatmessageDescPlatform := chatmessageFields[1].Descriptor()
	// chatmessage.DefaultPlatform holds the default value on creation for the platform field.
	chatmessage.DefaultPlatform = chatmessageDescPlatform.Default.(string)
	// chatmessage.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	chatmessage.PlatformValidator = chatmessageDescPlatform.Validators[0].(func(string) error)
	// chatmessageDescPlatformMessageID is the schema descriptor for platform_message_id field.
	chatmessageDescPlatformMessageID := chatmessageFields[2].Descriptor()
	// chatmessage.DefaultPlatformMessageID holds the default value on creation for the platform_message_id field.
	chatmessage.DefaultPlatformMessageID = chatmessageDescPlatformMessageID.Default.(string)
	// chatmessage.PlatformMessageIDValidator is a validator for the "platform_message_id" field. It is called by the builders before save.
	chatmessage.PlatformMessageIDValidator = chatmessageDescPlatformMessageID.Validators[0].(func(string) error)
	// chatmessageDescFromID is the schema descriptor for from_id field.
	chatmessageDescFromID := chatmessageFields[3].Descriptor()
	// chatmessage.DefaultFromID holds the default value on creation for the from_id field.
	chatmessage.DefaultFromID = chatmessageDescFromID.Default.(string)
	// chatmessage.FromIDValidator is a validator for the "from_id" field. It is called by the builders before save.
	chatmessage.FromIDValidator = chatmessageDescFromID.Validators[0].(func(string) error)
	// chatmessageDescFromName is the schema descriptor for from_name field.
	chatmessageDescFromName := chatmessageFields[4].Descriptor()
	// chatmessage.DefaultFromName holds the default value on creation for the from_name field.
	chatmessage.DefaultFromName = chatmessageDescFromName.Default.(string)
	// chatmessage.FromNameValidator is a validator for the "from_name" field. It is called by the builders before save.
	chatmessage.FromNameValidator = chatmessageDescFromName.Validators[0].(func(string) error)
	// chatmessageDescInChatID is the schema descriptor for in_chat_id field.
	chatmessageDescInChatID := chatmessageFields[7].Descriptor()
	// chatmessage.DefaultInChatID holds the default value on creation for the in_chat_id field.
	chatmessage.DefaultInChatID = chatmessageDescInChatID.Default.(string)
	// chatmessage.InChatIDValidator is a validator for the "in_chat_id" field. It is called by the builders before save.
	chatmessage.InChatIDValidator = chatmessageDescInChatID.Validators[0].(func(string) error)
	// chatmessageDescInChatType is the schema descriptor for in_chat_type field.
	chatmessageDescInChatType := chatmessageFields[8].Descriptor()
	// chatmessage.DefaultInChatType holds the default value on creation for the in_chat_type field.
	chatmessage.DefaultInChatType = chatmessageDescInChatType.Default.(string)
	// chatmessage.InChatTypeValidator is a validator for the "in_chat_type" field. It is called by the builders before save.
	chatmessage.InChatTypeValidator = chatmessageDescInChatType.Validators[0].(func(string) error)
	// chatmessageDescContent is the schema descriptor for content field.
	chatmessageDescContent := chatmessageFields[9].Descriptor()
	// chatmessage.DefaultContent holds the default value on creation for the content field.
	chatmessage.DefaultContent = chatmessageDescContent.Default.(string)
	// chatmessage.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	chatmessage.ContentValidator = chatmessageDescContent.Validators[0].(func(string) error)
	// chatmessageDescIsReply is the schema descriptor for is_reply field.
	chatmessageDescIsReply := chatmessageFields[10].Descriptor()
	// chatmessage.DefaultIsReply holds the default value on creation for the is_reply field.
	chatmessage.DefaultIsReply = chatmessageDescIsReply.Default.(bool)
	// chatmessageDescReplyToName is the schema descriptor for reply_to_name field.
	chatmessageDescReplyToName := chatmessageFields[11].Descriptor()
	// chatmessage.DefaultReplyToName holds the default value on creation for the reply_to_name field.
	chatmessage.DefaultReplyToName = chatmessageDescReplyToName.Default.(string)
	// chatmessage.ReplyToNameValidator is a validator for the "reply_to_name" field. It is called by the builders before save.
	chatmessage.ReplyToNameValidator = chatmessageDescReplyToName.Validators[0].(func(string) error)
	// chatmessageDescReplyToID is the schema descriptor for reply_to_id field.
	chatmessageDescReplyToID := chatmessageFields[12].Descriptor()
	// chatmessage.DefaultReplyToID holds the default value on creation for the reply_to_id field.
	chatmessage.DefaultReplyToID = chatmessageDescReplyToID.Default.(string)
	// chatmessage.ReplyToIDValidator is a validator for the "reply_to_id" field. It is called by the builders before save.
	chatmessage.ReplyToIDValidator = chatmessageDescReplyToID.Validators[0].(func(string) error)
	// chatmessageDescPlatformTimestamp is the schema descriptor for platform_timestamp field.
	chatmessageDescPlatformTimestamp := chatmessageFields[13].Descriptor()
	// chatmessage.DefaultPlatformTimestamp holds the default value on creation for the platform_timestamp field.
	chatmessage.DefaultPlatformTimestamp = chatmessageDescPlatformTimestamp.Default.(int64)
	// chatmessageDescJiebaTokens is the schema descriptor for jieba_tokens field.
	chatmessageDescJiebaTokens := chatmessageFields[17].Descriptor()
	// chatmessage.DefaultJiebaTokens holds the default value on creation for the jieba_tokens field.
	chatmessage.DefaultJiebaTokens = chatmessageDescJiebaTokens.Default.([]string)
	// chatmessageDescCreatedAt is the schema descriptor for created_at field.
	chatmessageDescCreatedAt := chatmessageFields[18].Descriptor()
	// chatmessage.DefaultCreatedAt holds the default value on creation for the created_at field.
	chatmessage.DefaultCreatedAt = chatmessageDescCreatedAt.Default.(func() int64)
	// chatmessageDescUpdatedAt is the schema descriptor for updated_at field.
	chatmessageDescUpdatedAt := chatmessageFields[19].Descriptor()
	// chatmessage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	chatmessage.DefaultUpdatedAt = chatmessageDescUpdatedAt.Default.(func() int64)
	// chatmessage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	chatmessage.UpdateDefaultUpdatedAt = chatmessageDescUpdatedAt.UpdateDefault.(func() int64)
	// chatmessageDescDeletedAt is the schema descriptor for deleted_at field.
	chatmessageDescDeletedAt := chatmessageFields[20].Descriptor()
	// chatmessage.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	chatmessage.DefaultDeletedAt = chatmessageDescDeletedAt.Default.(int64)
	// chatmessageDescID is the schema descriptor for id field.
	chatmessageDescID := chatmessageFields[0].Descriptor()
	// chatmessage.DefaultID holds the default value on creation for the id field.
	chatmessage.DefaultID = chatmessageDescID.Default.(func() uuid.UUID)
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescPlatform is the schema descriptor for platform field.
	eventDescPlatform := eventFields[1].Descriptor()
	// event.DefaultPlatform holds the default value on creation for the platform field.
	event.DefaultPlatform = eventDescPlatform.Default.(string)
	// event.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	event.PlatformValidator = eventDescPlatform.Validators[0].(func(string) error)
	// eventDescName is the schema descriptor for name field.
	eventDescName := eventFields[2].Descriptor()
	// event.DefaultName holds the default value on creation for the name field.
	event.DefaultName = eventDescName.Default.(string)
	// event.NameValidator is a validator for the "name" field. It is called by the builders before save.
	event.NameValidator = eventDescName.Validators[0].(func(string) error)
	// eventDescDescription is the schema descriptor for description field.
	eventDescDescription := eventFields[4].Descriptor()
	// event.DefaultDescription holds the default value on creation for the description field.
	event.DefaultDescription = eventDescDescription.Default.(string)
	// event.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	event.DescriptionValidator = eventDescDescription.Validators[0].(func(string) error)
	// eventDescFromName is the schema descriptor for from_name field.
	eventDescFromName := eventFields[5].Descriptor()
	// event.DefaultFromName holds the default value on creation for the from_name field.
	event.DefaultFromName = eventDescFromName.Default.(string)
	// event.FromNameValidator is a validator for the "from_name" field. It is called by the builders before save.
	event.FromNameValidator = eventDescFromName.Validators[0].(func(string) error)
	// eventDescInChatID is the schema descriptor for in_chat_id field.
	eventDescInChatID := eventFields[6].Descriptor()
	// event.DefaultInChatID holds the default value on creation for the in_chat_id field.
	event.DefaultInChatID = eventDescInChatID.Default.(string)
	// event.InChatIDValidator is a validator for the "in_chat_id" field. It is called by the builders before save.
	event.InChatIDValidator = eventDescInChatID.Validators[0].(func(string) error)
	// eventDescInChatType is the schema descriptor for in_chat_type field.
	eventDescInChatType := eventFields[7].Descriptor()
	// event.DefaultInChatType holds the default value on creation for the in_chat_type field.
	event.DefaultInChatType = eventDescInChatType.Default.(string)
	// event.InChatTypeValidator is a validator for the "in_chat_type" field. It is called by the builders before save.
	event.InChatTypeValidator = eventDescInChatType.Validators[0].(func(string) error)
	// eventDescPlatformTimestamp is the schema descriptor for platform_timestamp field.
	eventDescPlatformTimestamp := eventFields[8].Descriptor()
	// event.DefaultPlatformTimestamp holds the default value on creation for the platform_timestamp field.
	event.DefaultPlatformTimestamp = eventDescPlatformTimestamp.Default.(int64)
	// eventDescCreatedAt is the schema descriptor for created_at field.
	eventDescCreatedAt := eventFields[9].Descriptor()
	// event.DefaultCreatedAt holds the default value on creation for the created_at field.
	event.DefaultCreatedAt = eventDescCreatedAt.Default.(func() int64)
	// eventDescUpdatedAt is the schema descriptor for updated_at field.
	eventDescUpdatedAt := eventFields[10].Descriptor()
	// event.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	event.DefaultUpdatedAt = eventDescUpdatedAt.Default.(func() int64)
	// event.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	event.UpdateDefaultUpdatedAt = eventDescUpdatedAt.UpdateDefault.(func() int64)
	// eventDescID is the schema descriptor for id field.
	eventDescID := eventFields[0].Descriptor()
	// event.DefaultID holds the default value on creation for the id field.
	event.DefaultID = eventDescID.Default.(func() uuid.UUID)
	identityFields := schema.Identity{}.Fields()
	_ = identityFields
	// identityDescPlatform is the schema descriptor for platform field.
	identityDescPlatform := identityFields[1].Descriptor()
	// identity.DefaultPlatform holds the default value on creation for the platform field.
	identity.DefaultPlatform = identityDescPlatform.Default.(string)
	// identity.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	identity.PlatformValidator = identityDescPlatform.Validators[0].(func(string) error)
	// identityDescPlatformUserID is the schema descriptor for platform_user_id field.
	identityDescPlatformUserID := identityFields[2].Descriptor()
	// identity.DefaultPlatformUserID holds the default value on creation for the platform_user_id field.
	identity.DefaultPlatformUserID = identityDescPlatformUserID.Default.(string)
	// identity.PlatformUserIDValidator is a validator for the "platform_user_id" field. It is called by the builders before save.
	identity.PlatformUserIDValidator = identityDescPlatformUserID.Validators[0].(func(string) error)
	// identityDescUsername is the schema descriptor for username field.
	identityDescUsername := identityFields[3].Descriptor()
	// identity.DefaultUsername holds the default value on creation for the username field.
	identity.DefaultUsername = identityDescUsername.Default.(string)
	// identity.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	identity.UsernameValidator = identityDescUsername.Validators[0].(func(string) error)
	// identityDescDisplayName is the schema descriptor for display_name field.
	identityDescDisplayName := identityFields[4].Descriptor()
	// identity.DefaultDisplayName holds the default value on creation for the display_name field.
	identity.DefaultDisplayName = identityDescDisplayName.Default.(string)
	// identity.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	identity.DisplayNameValidator = identityDescDisplayName.Validators[0].(func(string) error)
	// identityDescProfilePhotoURL is the schema descriptor for profile_photo_url field.
	identityDescProfilePhotoURL := identityFields[5].Descriptor()
	// identity.DefaultProfilePhotoURL holds the default value on creation for the profile_photo_url field.
	identity.DefaultProfilePhotoURL = identityDescProfilePhotoURL.Default.(string)
	// identityDescCreatedAt is the schema descriptor for created_at field.
	identityDescCreatedAt := identityFields[7].Descriptor()
	// identity.DefaultCreatedAt holds the default value on creation for the created_at field.
	identity.DefaultCreatedAt = identityDescCreatedAt.Default.(func() int64)
	// identityDescUpdatedAt is the schema descriptor for updated_at field.
	identityDescUpdatedAt := identityFields[8].Descriptor()
	// identity.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	identity.DefaultUpdatedAt = identityDescUpdatedAt.Default.(func() int64)
	// identity.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	identity.UpdateDefaultUpdatedAt = identityDescUpdatedAt.UpdateDefault.(func() int64)
	// identityDescID is the schema descriptor for id field.
	identityDescID := identityFields[0].Descriptor()
	// identity.DefaultID holds the default value on creation for the id field.
	identity.DefaultID = identityDescID.Default.(func() uuid.UUID)
	joinedchatFields := schema.JoinedChat{}.Fields()
	_ = joinedchatFields
	// joinedchatDescPlatform is the schema descriptor for platform field.
	joinedchatDescPlatform := joinedchatFields[1].Descriptor()
	// joinedchat.DefaultPlatform holds the default value on creation for the platform field.
	joinedchat.DefaultPlatform = joinedchatDescPlatform.Default.(string)
	// joinedchat.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	joinedchat.PlatformValidator = joinedchatDescPlatform.Validators[0].(func(string) error)
	// joinedchatDescChatID is the schema descriptor for chat_id field.
	joinedchatDescChatID := joinedchatFields[2].Descriptor()
	// joinedchat.DefaultChatID holds the default value on creation for the chat_id field.
	joinedchat.DefaultChatID = joinedchatDescChatID.Default.(string)
	// joinedchat.ChatIDValidator is a validator for the "chat_id" field. It is called by the builders before save.
	joinedchat.ChatIDValidator = joinedchatDescChatID.Validators[0].(func(string) error)
	// joinedchatDescChatName is the schema descriptor for chat_name field.
	joinedchatDescChatName := joinedchatFields[3].Descriptor()
	// joinedchat.DefaultChatName holds the default value on creation for the chat_name field.
	joinedchat.DefaultChatName = joinedchatDescChatName.Default.(string)
	// joinedchat.ChatNameValidator is a validator for the "chat_name" field. It is called by the builders before save.
	joinedchat.ChatNameValidator = joinedchatDescChatName.Validators[0].(func(string) error)
	// joinedchatDescChatType is the schema descriptor for chat_type field.
	joinedchatDescChatType := joinedchatFields[4].Descriptor()
	// joinedchat.DefaultChatType holds the default value on creation for the chat_type field.
	joinedchat.DefaultChatType = joinedchatDescChatType.Default.(string)
	// joinedchat.ChatTypeValidator is a validator for the "chat_type" field. It is called by the builders before save.
	joinedchat.ChatTypeValidator = joinedchatDescChatType.Validators[0].(func(string) error)
	// joinedchatDescDialogDate is the schema descriptor for dialog_date field.
	joinedchatDescDialogDate := joinedchatFields[5].Descriptor()
	// joinedchat.DefaultDialogDate holds the default value on creation for the dialog_date field.
	joinedchat.DefaultDialogDate = joinedchatDescDialogDate.Default.(int64)
	// joinedchatDescCreatedAt is the schema descriptor for created_at field.
	joinedchatDescCreatedAt := joinedchatFields[6].Descriptor()
	// joinedchat.DefaultCreatedAt holds the default value on creation for the created_at field.
	joinedchat.DefaultCreatedAt = joinedchatDescCreatedAt.Default.(func() int64)
	// joinedchatDescUpdatedAt is the schema descriptor for updated_at field.
	joinedchatDescUpdatedAt := joinedchatFields[7].Descriptor()
	// joinedchat.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	joinedchat.DefaultUpdatedAt = joinedchatDescUpdatedAt.Default.(func() int64)
	// joinedchat.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	joinedchat.UpdateDefaultUpdatedAt = joinedchatDescUpdatedAt.UpdateDefault.(func() int64)
	// joinedchatDescID is the schema descriptor for id field.
	joinedchatDescID := joinedchatFields[0].Descriptor()
	// joinedchat.DefaultID holds the default value on creation for the id field.
	joinedchat.DefaultID = joinedchatDescID.Default.(func() uuid.UUID)
}
