// Code generated by ent, DO NOT EDIT.

package chatmessage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the chatmessage type in the database.
	Label = "chat_message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldPlatformMessageID holds the string denoting the platform_message_id field in the database.
	FieldPlatformMessageID = "platform_message_id"
	// FieldFromID holds the string denoting the from_id field in the database.
	FieldFromID = "from_id"
	// FieldFromName holds the string denoting the from_name field in the database.
	FieldFromName = "from_name"
	// FieldFromUserUUID holds the string denoting the from_user_uuid field in the database.
	FieldFromUserUUID = "from_user_uuid"
	// FieldOwnerAccountID holds the string denoting the owner_account_id field in the database.
	FieldOwnerAccountID = "owner_account_id"
	// FieldInChatID holds the string denoting the in_chat_id field in the database.
	FieldInChatID = "in_chat_id"
	// FieldInChatType holds the string denoting the in_chat_type field in the database.
	FieldInChatType = "in_chat_type"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldIsReply holds the string denoting the is_reply field in the database.
	FieldIsReply = "is_reply"
	// FieldReplyToName holds the string denoting the reply_to_name field in the database.
	FieldReplyToName = "reply_to_name"
	// FieldReplyToID holds the string denoting the reply_to_id field in the database.
	FieldReplyToID = "reply_to_id"
	// FieldPlatformTimestamp holds the string denoting the platform_timestamp field in the database.
	FieldPlatformTimestamp = "platform_timestamp"
	// FieldContentVector1536 holds the string denoting the content_vector_1536 field in the database.
	FieldContentVector1536 = "content_vector_1536"
	// FieldContentVector1024 holds the string denoting the content_vector_1024 field in the database.
	FieldContentVector1024 = "content_vector_1024"
	// FieldContentVector768 holds the string denoting the content_vector_768 field in the database.
	FieldContentVector768 = "content_vector_768"
	// FieldJiebaTokens holds the string denoting the jieba_tokens field in the database.
	FieldJiebaTokens = "jieba_tokens"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// Table holds the table name of the chatmessage in the database.
	Table = "chat_messages"
)

// Columns holds all SQL columns for chatmessage fields.
var Columns = []string{
	FieldID,
	FieldPlatform,
	FieldPlatformMessageID,
	FieldFromID,
	FieldFromName,
	FieldFromUserUUID,
	FieldOwnerAccountID,
	FieldInChatID,
	FieldInChatType,
	FieldContent,
	FieldIsReply,
	FieldReplyToName,
	FieldReplyToID,
	FieldPlatformTimestamp,
	FieldContentVector1536,
	FieldContentVector1024,
	FieldContentVector768,
	FieldJiebaTokens,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DefaultPlatformMessageID holds the default value on creation for the "platform_message_id" field.
	DefaultPlatformMessageID string
	// PlatformMessageIDValidator is a validator for the "platform_message_id" field. It is called by the builders before save.
	PlatformMessageIDValidator func(string) error
	// DefaultFromID holds the default value on creation for the "from_id" field.
	DefaultFromID string
	// FromIDValidator is a validator for the "from_id" field. It is called by the builders before save.
	FromIDValidator func(string) error
	// DefaultFromName holds the default value on creation for the "from_name" field.
	DefaultFromName string
	// FromNameValidator is a validator for the "from_name" field. It is called by the builders before save.
	FromNameValidator func(string) error
	// DefaultInChatID holds the default value on creation for the "in_chat_id" field.
	DefaultInChatID string
	// InChatIDValidator is a validator for the "in_chat_id" field. It is called by the builders before save.
	InChatIDValidator func(string) error
	// DefaultInChatType holds the default value on creation for the "in_chat_type" field.
	DefaultInChatType string
	// InChatTypeValidator is a validator for the "in_chat_type" field. It is called by the builders before save.
	InChatTypeValidator func(string) error
	// DefaultContent holds the default value on creation for the "content" field.
	DefaultContent string
	// ContentValidator is a validator for the "content" field. It is called by the builders before save.
	ContentValidator func(string) error
	// DefaultIsReply holds the default value on creation for the "is_reply" field.
	DefaultIsReply bool
	// DefaultReplyToName holds the default value on creation for the "reply_to_name" field.
	DefaultReplyToName string
	// ReplyToNameValidator is a validator for the "reply_to_name" field. It is called by the builders before save.
	ReplyToNameValidator func(string) error
	// DefaultReplyToID holds the default value on creation for the "reply_to_id" field.
	DefaultReplyToID string
	// ReplyToIDValidator is a validator for the "reply_to_id" field. It is called by the builders before save.
	ReplyToIDValidator func(string) error
	// DefaultPlatformTimestamp holds the default value on creation for the "platform_timestamp" field.
	DefaultPlatformTimestamp int64
	// DefaultJiebaTokens holds the default value on creation for the "jieba_tokens" field.
	DefaultJiebaTokens []string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ChatMessage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByPlatformMessageID orders the results by the platform_message_id field.
func ByPlatformMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatformMessageID, opts...).ToFunc()
}

// ByFromID orders the results by the from_id field.
func ByFromID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromID, opts...).ToFunc()
}

// ByFromName orders the results by the from_name field.
func ByFromName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromName, opts...).ToFunc()
}

// ByFromUserUUID orders the results by the from_user_uuid field.
func ByFromUserUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromUserUUID, opts...).ToFunc()
}

// ByOwnerAccountID orders the results by the owner_account_id field.
func ByOwnerAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerAccountID, opts...).ToFunc()
}

// ByInChatID orders the results by the in_chat_id field.
func ByInChatID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInChatID, opts...).ToFunc()
}

// ByInChatType orders the results by the in_chat_type field.
func ByInChatType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInChatType, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByIsReply orders the results by the is_reply field.
func ByIsReply(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsReply, opts...).ToFunc()
}

// ByReplyToName orders the results by the reply_to_name field.
func ByReplyToName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReplyToName, opts...).ToFunc()
}

// ByReplyToID orders the results by the reply_to_id field.
func ByReplyToID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReplyToID, opts...).ToFunc()
}

// ByPlatformTimestamp orders the results by the platform_timestamp field.
func ByPlatformTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatformTimestamp, opts...).ToFunc()
}

// ByContentVector1536 orders the results by the content_vector_1536 field.
func ByContentVector1536(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentVector1536, opts...).ToFunc()
}

// ByContentVector1024 orders the results by the content_vector_1024 field.
func ByContentVector1024(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentVector1024, opts...).ToFunc()
}

// ByContentVector768 orders the results by the content_vector_768 field.
func ByContentVector768(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentVector768, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}
