// Code generated by ent, DO NOT EDIT.

package chatmessage

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/luoling8192/adk-agent/ent/predicate"
	pgvector "github.com/pgvector/pgvector-go"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLTE(FieldID, id))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldPlatform, v))
}

// PlatformMessageID applies equality check predicate on the "platform_message_id" field. It's identical to PlatformMessageIDEQ.
func PlatformMessageID(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldPlatformMessageID, v))
}

// FromID applies equality check predicate on the "from_id" field. It's identical to FromIDEQ.
func FromID(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldFromID, v))
}

// FromName applies equality check predicate on the "from_name" field. It's identical to FromNameEQ.
func FromName(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldFromName, v))
}

// FromUserUUID applies equality check predicate on the "from_user_uuid" field. It's identical to FromUserUUIDEQ.
func FromUserUUID(v uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldFromUserUUID, v))
}

// OwnerAccountID applies equality check predicate on the "owner_account_id" field. It's identical to OwnerAccountIDEQ.
func OwnerAccountID(v uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldOwnerAccountID, v))
}

// InChatID applies equality check predicate on the "in_chat_id" field. It's identical to InChatIDEQ.
func InChatID(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldInChatID, v))
}

// InChatType applies equality check predicate on the "in_chat_type" field. It's identical to InChatTypeEQ.
func InChatType(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldInChatType, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldContent, v))
}

// IsReply applies equality check predicate on the "is_reply" field. It's identical to IsReplyEQ.
func IsReply(v bool) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldIsReply, v))
}

// ReplyToName applies equality check predicate on the "reply_to_name" field. It's identical to ReplyToNameEQ.
func ReplyToName(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldReplyToName, v))
}

// ReplyToID applies equality check predicate on the "reply_to_id" field. It's identical to ReplyToIDEQ.
func ReplyToID(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldReplyToID, v))
}

// PlatformTimestamp applies equality check predicate on the "platform_timestamp" field. It's identical to PlatformTimestampEQ.
func PlatformTimestamp(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldPlatformTimestamp, v))
}

// ContentVector1536 applies equality check predicate on the "content_vector_1536" field. It's identical to ContentVector1536EQ.
func ContentVector1536(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldContentVector1536, v))
}

// ContentVector1024 applies equality check predicate on the "content_vector_1024" field. It's identical to ContentVector1024EQ.
func ContentVector1024(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldContentVector1024, v))
}

// ContentVector768 applies equality check predicate on the "content_vector_768" field. It's identical to ContentVector768EQ.
func ContentVector768(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldContentVector768, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldDeletedAt, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldContainsFold(FieldPlatform, v))
}

// PlatformMessageIDEQ applies the EQ predicate on the "platform_message_id" field.
func PlatformMessageIDEQ(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldPlatformMessageID, v))
}

// PlatformMessageIDNEQ applies the NEQ predicate on the "platform_message_id" field.
func PlatformMessageIDNEQ(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldPlatformMessageID, v))
}

// PlatformMessageIDIn applies the In predicate on the "platform_message_id" field.
func PlatformMessageIDIn(vs ...string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIn(FieldPlatformMessageID, vs...))
}

// PlatformMessageIDNotIn applies the NotIn predicate on the "platform_message_id" field.
func PlatformMessageIDNotIn(vs ...string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotIn(FieldPlatformMessageID, vs...))
}

// PlatformMessageIDGT applies the GT predicate on the "platform_message_id" field.
func PlatformMessageIDGT(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGT(FieldPlatformMessageID, v))
}

// PlatformMessageIDGTE applies the GTE predicate on the "platform_message_id" field.
func PlatformMessageIDGTE(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGTE(FieldPlatformMessageID, v))
}

// PlatformMessageIDLT applies the LT predicate on the "platform_message_id" field.
func PlatformMessageIDLT(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLT(FieldPlatformMessageID, v))
}

// PlatformMessageIDLTE applies the LTE predicate on the "platform_message_id" field.
func PlatformMessageIDLTE(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLTE(FieldPlatformMessageID, v))
}

// PlatformMessageIDContains applies the Contains predicate on the "platform_message_id" field.
func PlatformMessageIDContains(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldContains(FieldPlatformMessageID, v))
}

// PlatformMessageIDHasPrefix applies the HasPrefix predicate on the "platform_message_id" field.
func PlatformMessageIDHasPrefix(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldHasPrefix(FieldPlatformMessageID, v))
}

// PlatformMessageIDHasSuffix applies the HasSuffix predicate on the "platform_message_id" field.
func PlatformMessageIDHasSuffix(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldHasSuffix(FieldPlatformMessageID, v))
}

// PlatformMessageIDEqualFold applies the EqualFold predicate on the "platform_message_id" field.
func PlatformMessageIDEqualFold(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEqualFold(FieldPlatformMessageID, v))
}

// PlatformMessageIDContainsFold applies the ContainsFold predicate on the "platform_message_id" field.
func PlatformMessageIDContainsFold(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldContainsFold(FieldPlatformMessageID, v))
}

// FromIDEQ applies the EQ predicate on the "from_id" field.
func FromIDEQ(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldFromID, v))
}

// FromIDNEQ applies the NEQ predicate on the "from_id" field.
func FromIDNEQ(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldFromID, v))
}

// FromIDIn applies the In predicate on the "from_id" field.
func FromIDIn(vs ...string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIn(FieldFromID, vs...))
}

// FromIDNotIn applies the NotIn predicate on the "from_id" field.
func FromIDNotIn(vs ...string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotIn(FieldFromID, vs...))
}

// FromIDGT applies the GT predicate on the "from_id" field.
func FromIDGT(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGT(FieldFromID, v))
}

// FromIDGTE applies the GTE predicate on the "from_id" field.
func FromIDGTE(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGTE(FieldFromID, v))
}

// FromIDLT applies the LT predicate on the "from_id" field.
func FromIDLT(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLT(FieldFromID, v))
}

// FromIDLTE applies the LTE predicate on the "from_id" field.
func FromIDLTE(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLTE(FieldFromID, v))
}

// FromIDContains applies the Contains predicate on the "from_id" field.
func FromIDContains(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldContains(FieldFromID, v))
}

// FromIDHasPrefix applies the HasPrefix predicate on the "from_id" field.
func FromIDHasPrefix(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldHasPrefix(FieldFromID, v))
}

// FromIDHasSuffix applies the HasSuffix predicate on the "from_id" field.
func FromIDHasSuffix(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldHasSuffix(FieldFromID, v))
}

// FromIDEqualFold applies the EqualFold predicate on the "from_id" field.
func FromIDEqualFold(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEqualFold(FieldFromID, v))
}

// FromIDContainsFold applies the ContainsFold predicate on the "from_id" field.
func FromIDContainsFold(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldContainsFold(FieldFromID, v))
}

// FromNameEQ applies the EQ predicate on the "from_name" field.
func FromNameEQ(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldFromName, v))
}

// FromNameNEQ applies the NEQ predicate on the "from_name" field.
func FromNameNEQ(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldFromName, v))
}

// FromNameIn applies the In predicate on the "from_name" field.
func FromNameIn(vs ...string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIn(FieldFromName, vs...))
}

// FromNameNotIn applies the NotIn predicate on the "from_name" field.
func FromNameNotIn(vs ...string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotIn(FieldFromName, vs...))
}

// FromNameGT applies the GT predicate on the "from_name" field.
func FromNameGT(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGT(FieldFromName, v))
}

// FromNameGTE applies the GTE predicate on the "from_name" field.
func FromNameGTE(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGTE(FieldFromName, v))
}

// FromNameLT applies the LT predicate on the "from_name" field.
func FromNameLT(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLT(FieldFromName, v))
}

// FromNameLTE applies the LTE predicate on the "from_name" field.
func FromNameLTE(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLTE(FieldFromName, v))
}

// FromNameContains applies the Contains predicate on the "from_name" field.
func FromNameContains(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldContains(FieldFromName, v))
}

// FromNameHasPrefix applies the HasPrefix predicate on the "from_name" field.
func FromNameHasPrefix(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldHasPrefix(FieldFromName, v))
}

// FromNameHasSuffix applies the HasSuffix predicate on the "from_name" field.
func FromNameHasSuffix(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldHasSuffix(FieldFromName, v))
}

// FromNameEqualFold applies the EqualFold predicate on the "from_name" field.
func FromNameEqualFold(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEqualFold(FieldFromName, v))
}

// FromNameContainsFold applies the ContainsFold predicate on the "from_name" field.
func FromNameContainsFold(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldContainsFold(FieldFromName, v))
}

// FromUserUUIDEQ applies the EQ predicate on the "from_user_uuid" field.
func FromUserUUIDEQ(v uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldFromUserUUID, v))
}

// FromUserUUIDNEQ applies the NEQ predicate on the "from_user_uuid" field.
func FromUserUUIDNEQ(v uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldFromUserUUID, v))
}

// FromUserUUIDIn applies the In predicate on the "from_user_uuid" field.
func FromUserUUIDIn(vs ...uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIn(FieldFromUserUUID, vs...))
}

// FromUserUUIDNotIn applies the NotIn predicate on the "from_user_uuid" field.
func FromUserUUIDNotIn(vs ...uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotIn(FieldFromUserUUID, vs...))
}

// FromUserUUIDGT applies the GT predicate on the "from_user_uuid" field.
func FromUserUUIDGT(v uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGT(FieldFromUserUUID, v))
}

// FromUserUUIDGTE applies the GTE predicate on the "from_user_uuid" field.
func FromUserUUIDGTE(v uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGTE(FieldFromUserUUID, v))
}

// FromUserUUIDLT applies the LT predicate on the "from_user_uuid" field.
func FromUserUUIDLT(v uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLT(FieldFromUserUUID, v))
}

// FromUserUUIDLTE applies the LTE predicate on the "from_user_uuid" field.
func FromUserUUIDLTE(v uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLTE(FieldFromUserUUID, v))
}

// FromUserUUIDIsNil applies the IsNil predicate on the "from_user_uuid" field.
func FromUserUUIDIsNil() predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIsNull(FieldFromUserUUID))
}

// FromUserUUIDNotNil applies the NotNil predicate on the "from_user_uuid" field.
func FromUserUUIDNotNil() predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotNull(FieldFromUserUUID))
}

// OwnerAccountIDEQ applies the EQ predicate on the "owner_account_id" field.
func OwnerAccountIDEQ(v uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldOwnerAccountID, v))
}

// OwnerAccountIDNEQ applies the NEQ predicate on the "owner_account_id" field.
func OwnerAccountIDNEQ(v uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldOwnerAccountID, v))
}

// OwnerAccountIDIn applies the In predicate on the "owner_account_id" field.
func OwnerAccountIDIn(vs ...uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIn(FieldOwnerAccountID, vs...))
}

// OwnerAccountIDNotIn applies the NotIn predicate on the "owner_account_id" field.
func OwnerAccountIDNotIn(vs ...uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotIn(FieldOwnerAccountID, vs...))
}

// OwnerAccountIDGT applies the GT predicate on the "owner_account_id" field.
func OwnerAccountIDGT(v uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGT(FieldOwnerAccountID, v))
}

// OwnerAccountIDGTE applies the GTE predicate on the "owner_account_id" field.
func OwnerAccountIDGTE(v uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGTE(FieldOwnerAccountID, v))
}

// OwnerAccountIDLT applies the LT predicate on the "owner_account_id" field.
func OwnerAccountIDLT(v uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLT(FieldOwnerAccountID, v))
}

// OwnerAccountIDLTE applies the LTE predicate on the "owner_account_id" field.
func OwnerAccountIDLTE(v uuid.UUID) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLTE(FieldOwnerAccountID, v))
}

// OwnerAccountIDIsNil applies the IsNil predicate on the "owner_account_id" field.
func OwnerAccountIDIsNil() predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIsNull(FieldOwnerAccountID))
}

// OwnerAccountIDNotNil applies the NotNil predicate on the "owner_account_id" field.
func OwnerAccountIDNotNil() predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotNull(FieldOwnerAccountID))
}

// InChatIDEQ applies the EQ predicate on the "in_chat_id" field.
func InChatIDEQ(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldInChatID, v))
}

// InChatIDNEQ applies the NEQ predicate on the "in_chat_id" field.
func InChatIDNEQ(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldInChatID, v))
}

// InChatIDIn applies the In predicate on the "in_chat_id" field.
func InChatIDIn(vs ...string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIn(FieldInChatID, vs...))
}

// InChatIDNotIn applies the NotIn predicate on the "in_chat_id" field.
func InChatIDNotIn(vs ...string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotIn(FieldInChatID, vs...))
}

// InChatIDGT applies the GT predicate on the "in_chat_id" field.
func InChatIDGT(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGT(FieldInChatID, v))
}

// InChatIDGTE applies the GTE predicate on the "in_chat_id" field.
func InChatIDGTE(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGTE(FieldInChatID, v))
}

// InChatIDLT applies the LT predicate on the "in_chat_id" field.
func InChatIDLT(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLT(FieldInChatID, v))
}

// InChatIDLTE applies the LTE predicate on the "in_chat_id" field.
func InChatIDLTE(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLTE(FieldInChatID, v))
}

// InChatIDContains applies the Contains predicate on the "in_chat_id" field.
func InChatIDContains(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldContains(FieldInChatID, v))
}

// InChatIDHasPrefix applies the HasPrefix predicate on the "in_chat_id" field.
func InChatIDHasPrefix(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldHasPrefix(FieldInChatID, v))
}

// InChatIDHasSuffix applies the HasSuffix predicate on the "in_chat_id" field.
func InChatIDHasSuffix(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldHasSuffix(FieldInChatID, v))
}

// InChatIDEqualFold applies the EqualFold predicate on the "in_chat_id" field.
func InChatIDEqualFold(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEqualFold(FieldInChatID, v))
}

// InChatIDContainsFold applies the ContainsFold predicate on the "in_chat_id" field.
func InChatIDContainsFold(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldContainsFold(FieldInChatID, v))
}

// InChatTypeEQ applies the EQ predicate on the "in_chat_type" field.
func InChatTypeEQ(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldInChatType, v))
}

// InChatTypeNEQ applies the NEQ predicate on the "in_chat_type" field.
func InChatTypeNEQ(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldInChatType, v))
}

// InChatTypeIn applies the In predicate on the "in_chat_type" field.
func InChatTypeIn(vs ...string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIn(FieldInChatType, vs...))
}

// InChatTypeNotIn applies the NotIn predicate on the "in_chat_type" field.
func InChatTypeNotIn(vs ...string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotIn(FieldInChatType, vs...))
}

// InChatTypeGT applies the GT predicate on the "in_chat_type" field.
func InChatTypeGT(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGT(FieldInChatType, v))
}

// InChatTypeGTE applies the GTE predicate on the "in_chat_type" field.
func InChatTypeGTE(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGTE(FieldInChatType, v))
}

// InChatTypeLT applies the LT predicate on the "in_chat_type" field.
func InChatTypeLT(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLT(FieldInChatType, v))
}

// InChatTypeLTE applies the LTE predicate on the "in_chat_type" field.
func InChatTypeLTE(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLTE(FieldInChatType, v))
}

// InChatTypeContains applies the Contains predicate on the "in_chat_type" field.
func InChatTypeContains(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldContains(FieldInChatType, v))
}

// InChatTypeHasPrefix applies the HasPrefix predicate on the "in_chat_type" field.
func InChatTypeHasPrefix(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldHasPrefix(FieldInChatType, v))
}

// InChatTypeHasSuffix applies the HasSuffix predicate on the "in_chat_type" field.
func InChatTypeHasSuffix(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldHasSuffix(FieldInChatType, v))
}

// InChatTypeEqualFold applies the EqualFold predicate on the "in_chat_type" field.
func InChatTypeEqualFold(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEqualFold(FieldInChatType, v))
}

// InChatTypeContainsFold applies the ContainsFold predicate on the "in_chat_type" field.
func InChatTypeContainsFold(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldContainsFold(FieldInChatType, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldContainsFold(FieldContent, v))
}

// IsReplyEQ applies the EQ predicate on the "is_reply" field.
func IsReplyEQ(v bool) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldIsReply, v))
}

// IsReplyNEQ applies the NEQ predicate on the "is_reply" field.
func IsReplyNEQ(v bool) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldIsReply, v))
}

// ReplyToNameEQ applies the EQ predicate on the "reply_to_name" field.
func ReplyToNameEQ(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldReplyToName, v))
}

// ReplyToNameNEQ applies the NEQ predicate on the "reply_to_name" field.
func ReplyToNameNEQ(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldReplyToName, v))
}

// ReplyToNameIn applies the In predicate on the "reply_to_name" field.
func ReplyToNameIn(vs ...string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIn(FieldReplyToName, vs...))
}

// ReplyToNameNotIn applies the NotIn predicate on the "reply_to_name" field.
func ReplyToNameNotIn(vs ...string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotIn(FieldReplyToName, vs...))
}

// ReplyToNameGT applies the GT predicate on the "reply_to_name" field.
func ReplyToNameGT(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGT(FieldReplyToName, v))
}

// ReplyToNameGTE applies the GTE predicate on the "reply_to_name" field.
func ReplyToNameGTE(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGTE(FieldReplyToName, v))
}

// ReplyToNameLT applies the LT predicate on the "reply_to_name" field.
func ReplyToNameLT(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLT(FieldReplyToName, v))
}

// ReplyToNameLTE applies the LTE predicate on the "reply_to_name" field.
func ReplyToNameLTE(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLTE(FieldReplyToName, v))
}

// ReplyToNameContains applies the Contains predicate on the "reply_to_name" field.
func ReplyToNameContains(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldContains(FieldReplyToName, v))
}

// ReplyToNameHasPrefix applies the HasPrefix predicate on the "reply_to_name" field.
func ReplyToNameHasPrefix(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldHasPrefix(FieldReplyToName, v))
}

// ReplyToNameHasSuffix applies the HasSuffix predicate on the "reply_to_name" field.
func ReplyToNameHasSuffix(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldHasSuffix(FieldReplyToName, v))
}

// ReplyToNameEqualFold applies the EqualFold predicate on the "reply_to_name" field.
func ReplyToNameEqualFold(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEqualFold(FieldReplyToName, v))
}

// ReplyToNameContainsFold applies the ContainsFold predicate on the "reply_to_name" field.
func ReplyToNameContainsFold(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldContainsFold(FieldReplyToName, v))
}

// ReplyToIDEQ applies the EQ predicate on the "reply_to_id" field.
func ReplyToIDEQ(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldReplyToID, v))
}

// ReplyToIDNEQ applies the NEQ predicate on the "reply_to_id" field.
func ReplyToIDNEQ(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldReplyToID, v))
}

// ReplyToIDIn applies the In predicate on the "reply_to_id" field.
func ReplyToIDIn(vs ...string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIn(FieldReplyToID, vs...))
}

// ReplyToIDNotIn applies the NotIn predicate on the "reply_to_id" field.
func ReplyToIDNotIn(vs ...string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotIn(FieldReplyToID, vs...))
}

// ReplyToIDGT applies the GT predicate on the "reply_to_id" field.
func ReplyToIDGT(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGT(FieldReplyToID, v))
}

// ReplyToIDGTE applies the GTE predicate on the "reply_to_id" field.
func ReplyToIDGTE(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGTE(FieldReplyToID, v))
}

// ReplyToIDLT applies the LT predicate on the "reply_to_id" field.
func ReplyToIDLT(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLT(FieldReplyToID, v))
}

// ReplyToIDLTE applies the LTE predicate on the "reply_to_id" field.
func ReplyToIDLTE(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLTE(FieldReplyToID, v))
}

// ReplyToIDContains applies the Contains predicate on the "reply_to_id" field.
func ReplyToIDContains(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldContains(FieldReplyToID, v))
}

// ReplyToIDHasPrefix applies the HasPrefix predicate on the "reply_to_id" field.
func ReplyToIDHasPrefix(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldHasPrefix(FieldReplyToID, v))
}

// ReplyToIDHasSuffix applies the HasSuffix predicate on the "reply_to_id" field.
func ReplyToIDHasSuffix(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldHasSuffix(FieldReplyToID, v))
}

// ReplyToIDEqualFold applies the EqualFold predicate on the "reply_to_id" field.
func ReplyToIDEqualFold(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEqualFold(FieldReplyToID, v))
}

// ReplyToIDContainsFold applies the ContainsFold predicate on the "reply_to_id" field.
func ReplyToIDContainsFold(v string) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldContainsFold(FieldReplyToID, v))
}

// PlatformTimestampEQ applies the EQ predicate on the "platform_timestamp" field.
func PlatformTimestampEQ(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldPlatformTimestamp, v))
}

// PlatformTimestampNEQ applies the NEQ predicate on the "platform_timestamp" field.
func PlatformTimestampNEQ(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldPlatformTimestamp, v))
}

// PlatformTimestampIn applies the In predicate on the "platform_timestamp" field.
func PlatformTimestampIn(vs ...int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIn(FieldPlatformTimestamp, vs...))
}

// PlatformTimestampNotIn applies the NotIn predicate on the "platform_timestamp" field.
func PlatformTimestampNotIn(vs ...int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotIn(FieldPlatformTimestamp, vs...))
}

// PlatformTimestampGT applies the GT predicate on the "platform_timestamp" field.
func PlatformTimestampGT(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGT(FieldPlatformTimestamp, v))
}

// PlatformTimestampGTE applies the GTE predicate on the "platform_timestamp" field.
func PlatformTimestampGTE(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGTE(FieldPlatformTimestamp, v))
}

// PlatformTimestampLT applies the LT predicate on the "platform_timestamp" field.
func PlatformTimestampLT(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLT(FieldPlatformTimestamp, v))
}

// PlatformTimestampLTE applies the LTE predicate on the "platform_timestamp" field.
func PlatformTimestampLTE(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLTE(FieldPlatformTimestamp, v))
}

// ContentVector1536EQ applies the EQ predicate on the "content_vector_1536" field.
func ContentVector1536EQ(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldContentVector1536, v))
}

// ContentVector1536NEQ applies the NEQ predicate on the "content_vector_1536" field.
func ContentVector1536NEQ(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldContentVector1536, v))
}

// ContentVector1536In applies the In predicate on the "content_vector_1536" field.
func ContentVector1536In(vs ...pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIn(FieldContentVector1536, vs...))
}

// ContentVector1536NotIn applies the NotIn predicate on the "content_vector_1536" field.
func ContentVector1536NotIn(vs ...pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotIn(FieldContentVector1536, vs...))
}

// ContentVector1536GT applies the GT predicate on the "content_vector_1536" field.
func ContentVector1536GT(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGT(FieldContentVector1536, v))
}

// ContentVector1536GTE applies the GTE predicate on the "content_vector_1536" field.
func ContentVector1536GTE(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGTE(FieldContentVector1536, v))
}

// ContentVector1536LT applies the LT predicate on the "content_vector_1536" field.
func ContentVector1536LT(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLT(FieldContentVector1536, v))
}

// ContentVector1536LTE applies the LTE predicate on the "content_vector_1536" field.
func ContentVector1536LTE(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLTE(FieldContentVector1536, v))
}

// ContentVector1024EQ applies the EQ predicate on the "content_vector_1024" field.
func ContentVector1024EQ(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldContentVector1024, v))
}

// ContentVector1024NEQ applies the NEQ predicate on the "content_vector_1024" field.
func ContentVector1024NEQ(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldContentVector1024, v))
}

// ContentVector1024In applies the In predicate on the "content_vector_1024" field.
func ContentVector1024In(vs ...pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIn(FieldContentVector1024, vs...))
}

// ContentVector1024NotIn applies the NotIn predicate on the "content_vector_1024" field.
func ContentVector1024NotIn(vs ...pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotIn(FieldContentVector1024, vs...))
}

// ContentVector1024GT applies the GT predicate on the "content_vector_1024" field.
func ContentVector1024GT(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGT(FieldContentVector1024, v))
}

// ContentVector1024GTE applies the GTE predicate on the "content_vector_1024" field.
func ContentVector1024GTE(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGTE(FieldContentVector1024, v))
}

// ContentVector1024LT applies the LT predicate on the "content_vector_1024" field.
func ContentVector1024LT(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLT(FieldContentVector1024, v))
}

// ContentVector1024LTE applies the LTE predicate on the "content_vector_1024" field.
func ContentVector1024LTE(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLTE(FieldContentVector1024, v))
}

// ContentVector768EQ applies the EQ predicate on the "content_vector_768" field.
func ContentVector768EQ(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldContentVector768, v))
}

// ContentVector768NEQ applies the NEQ predicate on the "content_vector_768" field.
func ContentVector768NEQ(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldContentVector768, v))
}

// ContentVector768In applies the In predicate on the "content_vector_768" field.
func ContentVector768In(vs ...pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIn(FieldContentVector768, vs...))
}

// ContentVector768NotIn applies the NotIn predicate on the "content_vector_768" field.
func ContentVector768NotIn(vs ...pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotIn(FieldContentVector768, vs...))
}

// ContentVector768GT applies the GT predicate on the "content_vector_768" field.
func ContentVector768GT(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGT(FieldContentVector768, v))
}

// ContentVector768GTE applies the GTE predicate on the "content_vector_768" field.
func ContentVector768GTE(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGTE(FieldContentVector768, v))
}

// ContentVector768LT applies the LT predicate on the "content_vector_768" field.
func ContentVector768LT(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLT(FieldContentVector768, v))
}

// ContentVector768LTE applies the LTE predicate on the "content_vector_768" field.
func ContentVector768LTE(v pgvector.Vector) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLTE(FieldContentVector768, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int64) predicate.ChatMessage {
	return predicate.ChatMessage(sql.FieldLTE(FieldDeletedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChatMessage) predicate.ChatMessage {
	return predicate.ChatMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChatMessage) predicate.ChatMessage {
	return predicate.ChatMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChatMessage) predicate.ChatMessage {
	return predicate.ChatMessage(sql.NotPredicates(p))
}
