// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ChatMessage is the predicate function for chatmessage builders.
type ChatMessage func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Identity is the predicate function for identity builders.
type Identity func(*sql.Selector)

// JoinedChat is the predicate function for joinedchat builders.
type JoinedChat func(*sql.Selector)
